### ISSUE TITLE
add seasonal decomposition

### ISSUE THREAD

**Issue by logisticregress** [alkaline-ml/pmdarima#190]
**Is your feature request related to a problem? Please describe.**
provide a method to produce the seasonal decomposition

**Describe the solution you'd like**
a visual showing the trend, seasonality, and residual, similar to how its done in R.  Ensure visuals can be modified using Matplotlib, Seaborn or other. 

**Describe alternatives you've considered**
currently we have to use statsmodels to run separate script to produce the decomposition

**Comment by tgsmith61591** [comment]
This seems like a very reasonable feature request. Could you provide an example of the output you're looking for? Maybe the statsmodels snippet?

Thanks!

**Comment by tgsmith61591** [comment]
@logisticregress Can you respond to the question above please?
