### ISSUE TITLE
multiple seasonality support for FourierFeaturizer 

### ISSUE THREAD

**Issue by ihadanny** [alkaline-ml/pmdarima#195]
FourierFeaturizer supports only a single seasonality, many time series exhibit multiple seasonalities (e.g. daily and weekly).

the whole function is just 60 lines of R, can't be that difficult to port it to python, right?
https://github.com/robjhyndman/forecast/blob/c20567769e70b4c6fafa5f1d3eb68106b53c7f89/R/season.R

**Comment by ihadanny** [comment]
oops, come to think of it - maybe you guys simply meant I should use 2 featurizers in the same pipeline, like so?

```
pipeline.Pipeline([
            ("fourier_s", ppc.FourierFeaturizer(m=short_season, k=i)),
            ("fourier_l", ppc.FourierFeaturizer(m=long_season, k=j))
```

it doesn't solve the "Remove equivalent seasonal periods due to multiple seasonality" problem, but it's a start if it works...

**Comment by tgsmith61591** [comment]
I looked into this at one point and there was a reason I put it off that I can't remember (statsmodels support? I don't recall). I'll look into what it would take

**Comment by tgsmith61591** [comment]
Closing because this is currently solvable w fourier exog featurizer
