### ISSUE TITLE
Update requirements

### ISSUE THREAD

**Issue by felix-hilden** [alkaline-ml/pmdarima#265]
Hi, first of all thanks for working to make this package happen!

The package [requires](https://github.com/alkaline-ml/pmdarima/blob/master/setup.py#L243) a Python version of `3.5` or above. It also requires the discontinued `pathlib` package on PyPI. [Pathlib](https://docs.python.org/3/library/pathlib.html) has been a part of the standard library since `3.4`. And `six` is a package for Python 2-3 compatibility, but it uses `string_types` and `with_metaclass`, both of which have Python 3 only variants [[1](https://six.readthedocs.io/#six.string_types)] [[2](https://six.readthedocs.io/#six.add_metaclass)].

Is there something I've not quite understood? If not, should the requirements and code be updated? At the very least one could use [`pathlib2`](https://pypi.org/project/pathlib2/), which is the successor of `pathlib` on PyPI.

**Comment by tgsmith61591** [comment]
We did not always require python 3+, and for a long time supported python 2.7 as well. Much of the code you've mentioned is a remnant of that, and is being slowly replaced. Good catches though :-)

**Comment by felix-hilden** [comment]
Thanks for the quick reply! They don't seem like big things, but I know you must be busy with other things too. If the issue is not fixed during the weekend, can I shoot a PR to try to address it?

**Comment by tgsmith61591** [comment]
We welcome PRs!
