### ISSUE TITLE
Broken documentation link on pip page

### ISSUE THREAD

**Issue by MaxGhenis** [alkaline-ml/pmdarima#266]
From https://pypi.org/project/pyramid-arima:
>All of your questions and more (including examples and guides) can be answered by the [Pyramid documentation](https://www.alkaline-ml.com/pyramid). If not, always feel free to file an issue.

This points to https://www.alkaline-ml.com/pyramid which does not exist.

**Comment by MaxGhenis** [comment]
Oh that's no longer the right package. It's how I stumbled upon this though, maybe point people to the current one there? https://pypi.org/project/pmdarima/

**Comment by tgsmith61591** [comment]
We no longer make deployments to that PyPi. If you import that package you get:

```
    The 'pyramid' package will be migrating to a new namespace beginning in 
    version 1.0.0: 'pmdarima'. This is due to a package name collision with the
    Pyramid web framework. For more information, see Issue #34:
    
        https://github.com/tgsmith61591/pyramid/issues/34
        
    The package will subsequently be installable via the name 'pmdarima'; the
    only functional change to the user will be the import name. All imports
    from 'pyramid' will change to 'pmdarima'.
```

**Comment by tgsmith61591** [comment]
I added a redirect at http://alkaline-ml.com/pyramid so it will take you to the current documentation. 🙂 Eventually maybe we'll have it redirect to a landing page that shows you how to migrate to the new package name.
