### ISSUE TITLE
auto_arima IC values different after fitting with same orders

### ISSUE THREAD

**Issue by wanwoochang** [alkaline-ml/pmdarima#279]
I applied the auto_arima method onto a [dataset](https://fred.stlouisfed.org/series/INVCMRMT) and received the following trace output:

```
Fit ARIMA: order=(0, 1, 0) seasonal_order=(0, 0, 0, 0); AIC=5348.037, BIC=5355.181, Fit time=0.019 seconds
Fit ARIMA: order=(1, 1, 0) seasonal_order=(0, 0, 0, 0); AIC=5399.843, BIC=5410.560, Fit time=0.079 seconds
Fit ARIMA: order=(0, 1, 1) seasonal_order=(0, 0, 0, 0); AIC=5350.241, BIC=5360.957, Fit time=0.054 seconds
Fit ARIMA: order=(0, 1, 0) seasonal_order=(0, 0, 0, 0); AIC=5409.217, BIC=5412.789, Fit time=0.011 seconds
Fit ARIMA: order=(1, 1, 1) seasonal_order=(0, 0, 0, 0); AIC=5378.835, BIC=5393.124, Fit time=0.256 seconds
Total fit time: 0.424 seconds
```
Parameters used:
- information_criterion: aic
- start_p/q = 0
- max_p/q = 2
- seasonal = False
- stationary = False

The first fitting seems to correspond to fitting using the statsmodels ARIMA method, but the second fitting is using the statsmodels SARIMAX method. The 'Fit ARIMA' print-out was misleading, but more importantly, even with the information_criterion parameter set to use AIC the method chose SARIMAX over ARIMA. Is there a reason why this might be the case?

**Comment by tgsmith61591** [comment]
One has an intercept and the other doesn't. I actually have this fixed on a branch (better trace logging) and will have it fixed on the next release
