### ISSUE TITLE
cross_validate_predict

### ISSUE THREAD

**Issue by rkurio** [alkaline-ml/pmdarima#291]
**Is your feature request related to a problem? Please describe.**
I am not sure if there is a method under Cross-validation classes to get predicted values.

**Describe the solution you'd like**
Corresponding statsmodels link
[https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.cross_val_predict.html](url)

**Describe alternatives you've considered**
Currently choosing best model and running it again to get predictions.

**Comment by tgsmith61591** [comment]
Totally, this would be super valuable. We'll get this into the next release.

**Comment by tgsmith61591** [comment]
Merged in #293
