### ISSUE TITLE
Fourier featurizer

### ISSUE THREAD

**Issue by nanominimax** [alkaline-ml/pmdarima#299]
**Question**
I want to understand mechanism behind Fourier featurizer. 
I am following the example provided in documentation:
[pipeline example](http://alkaline-ml.com/pmdarima/1.5.1/auto_examples/example_pipeline.html#sphx-glr-auto-examples-example-pipeline-py)
Here, first the wind dataset is being preprocessed using FourierFeaturizer. Then auto arima is being used as final estimator. The fit_transform output of Fourier Featurizer is an array depending on the parameter value of "k". So is autoarima being fitted on each individual array in Fourier Featurizer?

**Comment by tgsmith61591** [comment]
The `FourierFeaturizer` is akin to a scikit-learn `TransformerMixin`. It applies a function to an input array, returning the transformed output. The purpose of Fourier feature in time series like this is to permit us to fit a seasonal time series without learning the seasonal order (P, D, Q), which can be expensive. In this case, it's decomposing the seasonal components of the input time series into Fourier components in a 2d matrix (see [this method](https://github.com/alkaline-ml/pmdarima/blob/master/pmdarima/preprocessing/exog/_fourier.pyx#L24)). The 2d features are then used as _exogenous_ input (additional variables the ARIMA algorithm learns from).

```python
import numpy as np
import pmdarima as pm
from pmdarima import preprocessing as ppc

# Load the data and split it into separate pieces
data = pm.datasets.load_wineind()
train, test = data[:150], data[150:]

four = ppc.FourierFeaturizer(m=12, k=4)
y_trans, x_trans = four.fit_transform(train)
```

The time series itself is unaffected by the Fourier featurizer, but a new 2d array is created:

```python
>>> y_trans is train
True
>>> x_trans
     FOURIER_S12-0  FOURIER_C12-0  FOURIER_S12-1  FOURIER_C12-1  FOURIER_S12-2  FOURIER_C12-2  FOURIER_S12-3  FOURIER_C12-3
0         0.500000   8.660254e-01   8.660254e-01       0.500000   1.000000e+00  -4.371139e-08   8.660254e-01      -0.500000
1         0.866025   5.000000e-01   8.660254e-01      -0.500000  -8.742278e-08  -1.000000e+00  -8.660255e-01      -0.500000
2         1.000000  -4.371139e-08  -8.742278e-08      -1.000000  -1.000000e+00   1.311342e-07   1.748456e-07       1.000000
3         0.866025  -5.000001e-01  -8.660255e-01      -0.500000   1.748456e-07   1.000000e+00   8.660253e-01      -0.500000
4         0.500000  -8.660254e-01  -8.660253e-01       0.500000   1.000000e+00  -2.185570e-07  -8.660255e-01      -0.500000
..             ...            ...            ...            ...            ...            ...            ...            ...
145       0.866026   4.999982e-01   8.660233e-01      -0.500004  -6.381863e-06  -1.000000e+00  -8.660297e-01      -0.499993
146       1.000000  -2.141858e-06  -4.283716e-06      -1.000000  -1.000000e+00   6.425574e-06   8.567432e-06       1.000000
147       0.866024  -5.000019e-01  -8.660276e-01      -0.499996   6.469286e-06   1.000000e+00   8.660211e-01      -0.500007
148       0.499998  -8.660265e-01  -8.660232e-01       0.500004   1.000000e+00  -6.512997e-06  -8.660297e-01      -0.499992
149      -0.000002  -1.000000e+00   4.371139e-06       1.000000  -6.556709e-06  -1.000000e+00   8.742278e-06       1.000000

[150 rows x 8 columns]
```

**Comment by nanominimax** [comment]
Thanks for the great explanation Taylor, it's much clear now. Just to clarify a little bit further, so in the pipeline example, the array we get from FourierFeaturizer is taken as exogenous parameter in auto_arima mode? I am asking this because I do not see it being explicitly assigned any value(exog = ? ) in the pipeline. Because it seems like, the data is first processed through FF and it is used as endogenous and not exogenous parameter. Please correct me if I am wrong.

**Comment by tgsmith61591** [comment]
> the array we get from FourierFeaturizer is taken as exogenous parameter in auto_arima model?

Yep, if you trace the `fit` in [the Pipeline](https://github.com/alkaline-ml/pmdarima/blob/master/pmdarima/pipeline.py#L210) class, you'll see it's provided. The `AutoARIMA` class is a wrapper for the `auto_arima` function that provides the `y` and `exogenous` arrays at fit time [here](https://github.com/alkaline-ml/pmdarima/blob/master/pmdarima/arima/auto.py#L120). Hope that makes more sense, and thanks for asking a great question!

**Comment by tgsmith61591** [comment]
Closing since it appears this has been answered.
