### ISSUE TITLE
auto_arima using all cores with stepwise=True

### ISSUE THREAD

**Issue by mohitmunjal** [alkaline-ml/pmdarima#301]
`arima = auto_arima(data, information_criterion = 'aicc', m = 12, suppress_warnings=True, error_action='ignore')`

I am using a machine with 12 cores. On using auto_arima with stepwise=True(default) and n_jobs=1(default), when I monitor my CPU usage using the "top" command, I see that the work is automatically getting distributed  to all 12 cores with only the parent process running between 1100-1200% CPU Capacity(i.e ~12 cores). 

This behaviour is unusual as with n_jobs=1, the work should be done by only 1 core. What am I missing here?

Please find the results of "top" command below: 
![image](https://user-images.githubusercontent.com/12641173/74906334-adab1a80-53d6-11ea-9897-c0efeca2f711.png)

I was able to reproduce similar usage pattern using the documentation example

```
import pyramid as pm
import numpy as np
import matplotlib.pyplot as plt

y = pm.datasets.load_wineind()
# Fit your model
model = pm.auto_arima(y, seasonal=True, m=12)
```
CPU Usage Pattern below for this test example:
![test_case_arima](https://user-images.githubusercontent.com/12641173/74917894-44cf9c80-53ee-11ea-9381-736b6d2c39e3.PNG)

Any idea why that may be the case?

**Versions:**
Linux-3.10.0-693.21.1.el7.x86_64-x86_64-with-redhat-7.4-Maipo
Python 3.6.8 |Anaconda, Inc.| (default, Dec 30 2018, 01:22:34) 
[GCC 7.3.0]
pyramid 0.9.0 -- (_very old version. Can this be an issue?_)
NumPy 1.16.3
SciPy 1.3.1
Scikit-Learn 0.19.1
Statsmodels 0.10.2

**My Problem use Case**
I have a list of 5000 clients and I have to run auto_arima for all of them. The model is to be eventually trained on client level i.e. my code will train a different model for the 5000 clients I have. I will be using multiprocessing to divide these clients among different cores. Eg. Process 1 does the computation for first 1000 clients, Process 2 does for next 1000 and so on parallely.

Since auto_arima is automatically using the resources of all cores(should not be the case), my client level multiprocessing approach is actually performing worse since the client level processes have to wait for the resources to get free.

Also, If you have any suggestion how this could be leveraged, I would be thankful.
 
I posted a question on stackoverflow as well and the discussion can be accessed here: https://stackoverflow.com/questions/60294725/python-sarima-model-is-automatically-using-all-cores-of-cpu-how

This is my first time posting a question on github. Please let me know if I can supply any other info.

**Comment by tgsmith61591** [comment]
Hey thanks for the report. We've seen similar behavior in other issues, and I've long been convinced that there is some manner of low-level parallelism implemented in the SciPy optimizers used under the hood. When `stepwise=True`, we don't use multiprocessing at all. We've toyed with the idea of removing the `n_jobs` parameter and forcing stepwise to remove confusion.

Unrelated, you are using an _extremely_ old version of the package. I'd recommend using the `pmdarima` package, which is the new namespace for this. See #34 for detailed background.

```
$ pip install pmdarima
```

Then

```python
import pmdarima as pm  # this is the only import that changes
import numpy as np
import matplotlib.pyplot as plt

y = pm.datasets.load_wineind()
# Fit your model
model = pm.auto_arima(y, seasonal=True, m=12)
```

**Comment by mohitmunjal** [comment]
Thanks @tgsmith61591 for clarifying.

**Comment by Skwal77** [comment]
@mohitmunjal @tgsmith61591 :
Hey, guys, 
have you found a way to efficiently manage Auto Arima on 5000 clients?

**Comment by mohitmunjal** [comment]
@Skwal77 Nope. I went ahead with how it's working currently in auto_arima. My use case required me to retrain the model once every month, and each auto_arima run on 5000 clients was taking 12-13 hrs with the specs I had, so I was okay with it.

**Comment by Skwal77** [comment]
Thanks @mohitmunjal

**Comment by eromoe** [comment]
@Skwal77 I was using spark to distribute auto_arima , but some jobs got memory error under stepwise=True .

**Comment by Kikokushijo** [comment]
@Skwal77, @mohitmunjal 

I think this is because of multithreading in numpy and scipy.

Adding 
```
os.environ['OPENBLAS_NUM_THREADS'] = '1'
os.environ['MKL_NUM_THREADS'] = '1'
```
before importing numpy, scipy and pmdarima can solve this issue.

I have 3000+ time series to forecast and I assign them to 96 cores.
After doing this, I am able to reach the real parallelization.

source: https://stackoverflow.com/questions/17053671/how-do-you-stop-numpy-from-multithreading

**Comment by vinson2233** [comment]
The solution from @Kikokushijo is already pretty good, but this will disable multithreading for numpy and pandas, making any operation inside the modeling function become really slow. 
I found this answer from https://stackoverflow.com/questions/30791550/limit-number-of-threads-in-numpy and basically what we need to do is :
```python
from threadpoolctl import threadpool_limits
with threadpool_limits(limits=1, user_api='blas'):
    model = pm.auto_arima(y, seasonal=True, m=12)
```

and now I able to reach true parallelization without sacrificing numpy multithreading capability for data processing.
