### ISSUE TITLE
Coefficient of exogenous variable SARIMAX

### ISSUE THREAD

**Issue by tdesilvam** [alkaline-ml/pmdarima#307]
My data set is hourly data (seasonal). I used pmdarima , auto.arma to fit a model with exogenous variable (SARIMAX). However, I don't get coefficient for exogenous variable. I get the same model that I fit without exogenous variable (SARIMA).

**Comment by tgsmith61591** [comment]
Could you please follow the issue template and share things like:
1. The code you executed
2. The output you expected
3. The output you actually received

**Comment by tdesilvam** [comment]
1. **Code executed**:
smodelT = pm.auto_arima(train[['load']],exogeneous=train[['temperature']], start_p=1, start_q=1,
                         test='adf',
                         max_p=3, max_q=3, m=24,
                         start_P=0, seasonal=True,
                         d=None, D=1, trace=True,
                         error_action='ignore',  
                         suppress_warnings=True, 
                         stepwise=True)

smodelT.summary()

3. **Output received**
y | 5548
SARIMAX(3, 0, 2)x(2, 1, [1], 24) | -33461.841
Mon, 09 Mar 2020 | 66943.682
03:49:31 | 67009.850
0 | 66966.756
- 5548 |  
opg


                  coef | std err | z | P>\|z\| | [0.025 | 0.975]
                      -- | -- | -- | -- | -- | --
intercept  0.0237 | 0.009 | 2.587 | 0.010 | 0.006 | 0.042
ar.L1        1.5515 | 0.064 | 24.301 | 0.000 | 1.426 | 1.677
ar.L2       -0.7742 | 0.107 | -7.208 | 0.000 | -0.985 | -0.564
ar.L3       0.1823 | 0.059 | 3.066 | 0.002 | 0.066 | 0.299
ma.L1    -0.5730 | 0.066 | -8.693 | 0.000 | -0.702 | -0.444
ma.L2    -0.0130 | 0.066 | 0.196 | 0.845 | -0.117 | 0.143
ar.S.L24  0.5098 | 0.008 | 65.215 | 0.000 | 0.495 | 0.525
ar.S.L48   0.3104 | 0.008 | 39.195 | 0.000 | 0.295 | 0.326
ma.S.L24  -0.9982 | 0.025 | -40.648 | 0.000 | -1.046 | -0.950
sigma2     1.051e+04 | 267.493 | 39.298 | 0.000 | 9987.616 | 1.1e+04

Ljung-Box (Q): | 117.04 |                 Jarque-Bera (JB): | 32502.60
 Prob(Q):        0.00 |                        Prob(JB): 0.00
Heteroskedasticity (H):1.22 |           Skew: -0.15
Prob(H) (two-sided): 0.00 |             Kurtosis:14.88

2. **Output expected** :
I attached my data set.
[df_FSdT.xlsx](https://github.com/alkaline-ml/pmdarima/files/4307253/df_FSdT.xlsx)

I want to forecast the 'load' variable, which is 24 hr demand. temperature is the exogenous variable. Data set was divided 0.85:0.15 for train:test

Thank you,
Thushara

**Comment by tgsmith61591** [comment]
That's only one model. Do you have the output from the other one (without the exogenous) that you mentioned?

**Comment by tdesilvam** [comment]
Model without exogenous variable:
1. **code executed:**
smodel = pm.auto_arima(train, start_p=1, start_q=1,
                         test='adf',
                         max_p=3, max_q=3, m=24,
                         start_P=0, seasonal=True,
                         d=None, D=1, trace=True,
                         error_action='ignore',  
                         suppress_warnings=True, 
                         stepwise=True)

smodel.summary()

2. **Output received:**
Deep variables:  y |    No.of observations:   5548
Model:    SARIMAX(2, 0, 3)x(2, 1, 1, 24) |     Log Likelihood:  -33463.128
AIC:  66946.256  |    BIC: 67012.425
Sample: 0 |        HQIC: 66969.331
- 5548

Covariance Type: | opg

                                 coef |    std err | z |     P>\|z\| | [0.025 | 0.975]
                               
intercept  0.0282     0.012        2.397       0.017       0.005        0.051
ar.L1	1.2359	0.130	9.536	0.000	0.982	1.490
ar.L2	-0.2870	0.118	-2.441	0.015	-0.517	-0.057
ma.L1	-0.2579	0.130	-1.977	0.048	-0.514	-0.002
ma.L2	-0.1717	0.013	-13.424	0.000	-0.197	-0.147
ma.L3	-0.0449	0.026	-1.757	0.079	-0.095	0.005
ar.S.L24	0.5124	0.008	65.901	0.000	0.497	0.528
ar.S.L48	0.3076	0.008	38.794	0.000	0.292	0.323
ma.S.L24	-0.9984	0.028	-35.549	0.000	-1.053	-0.943
sigma2	1.049e+04	301.593	34.779	0.000	9898.118	1.11e+04

Ljung-Box (Q): | 122.49 | Jarque-Bera (JB): | 31903.14
Prob(Q): 0.00 |               Prob(JB):0.00
Heteroskedasticity (H):1.22 |  Skew:  -0.15
Prob(H) (two-sided): 0.00 |      Kurtosis:14.77

Btw, I upgraded my statsmodels to  0.11.1 from 0.9.0 and re executed the codes. I got the similar result.
Thanks,
Thushara

**Comment by tgsmith61591** [comment]
I guess I'm still not understanding your problem. These are two different models (look at the summary numbers you provided). Also, the orders are different:
`(3,0,2)(2,1,1,24)` vs. `(2,0,3)(2,1,1,24)`.

What is the actual problem?

**Comment by tdesilvam** [comment]
I don't get a coefficient for the exogenous variable (x1). When I predict from two models, I get the same answers.

**Comment by tgsmith61591** [comment]
I can't replicate. Here's a toy example:

```python
>>> import pmdarima as pm
>>> import numpy as np
>>> y = pm.datasets.load_wineind()
>>> no_exog = pm.auto_arima(y, suppress_warnings=True, m=12)
>>> exog = pm.auto_arima(y, exogenous=np.random.RandomState(1).rand(y.shape[0], 2), suppress_warnings=True, m=12)
```

Summary of `no_exog`:

```
no_exog.summary()
Out[7]:
<class 'statsmodels.iolib.summary.Summary'>
"""
                                 Statespace Model Results
==========================================================================================
Dep. Variable:                                  y   No. Observations:                  176
Model:             SARIMAX(1, 1, 2)x(0, 1, 1, 12)   Log Likelihood               -1527.371
Date:                            Mon, 09 Mar 2020   AIC                           3066.742
Time:                                    11:54:00   BIC                           3085.305
Sample:                                         0   HQIC                          3074.278
                                            - 176
Covariance Type:                              opg
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
intercept   -100.7331     72.197     -1.395      0.163    -242.236      40.770
ar.L1         -0.5123      0.390     -1.312      0.189      -1.277       0.253
ma.L1         -0.0806      0.404     -0.200      0.842      -0.872       0.711
ma.L2         -0.4430      0.224     -1.978      0.048      -0.882      -0.004
ma.S.L12      -0.4025      0.054     -7.448      0.000      -0.508      -0.297
sigma2      7.663e+06    7.3e+05     10.495      0.000    6.23e+06    9.09e+06
===================================================================================
Ljung-Box (Q):                       48.70   Jarque-Bera (JB):                21.57
Prob(Q):                              0.16   Prob(JB):                         0.00
Heteroskedasticity (H):               1.18   Skew:                            -0.61
Prob(H) (two-sided):                  0.54   Kurtosis:                         4.31
===================================================================================

Warnings:
[1] Covariance matrix calculated using the outer product of gradients (complex-step).
[2] Covariance matrix is singular or near-singular, with condition number 8.14e+14. Standard errors may be unstable.
"""
```

Summary of `exog` (notice `x1` and `x2`):

```
exog.summary()
Out[8]:
<class 'statsmodels.iolib.summary.Summary'>
"""
                                 Statespace Model Results
==========================================================================================
Dep. Variable:                                  y   No. Observations:                  176
Model:             SARIMAX(4, 1, 0)x(1, 0, 1, 12)   Log Likelihood               -1670.465
Date:                            Mon, 09 Mar 2020   AIC                           3360.931
Time:                                    11:54:29   BIC                           3392.579
Sample:                                         0   HQIC                          3373.768
                                            - 176
Covariance Type:                              opg
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
intercept    -15.3993     30.887     -0.499      0.618     -75.936      45.138
x1           527.8112    775.203      0.681      0.496    -991.558    2047.181
x2         -2173.1189    608.761     -3.570      0.000   -3366.268    -979.970
ar.L1         -0.8994      0.055    -16.268      0.000      -1.008      -0.791
ar.L2         -0.8604      0.064    -13.352      0.000      -0.987      -0.734
ar.L3         -0.5326      0.071     -7.458      0.000      -0.673      -0.393
ar.L4         -0.2602      0.052     -5.046      0.000      -0.361      -0.159
ar.S.L12       0.9561      0.025     37.776      0.000       0.906       1.006
ma.S.L12      -0.5918      0.075     -7.903      0.000      -0.739      -0.445
sigma2      9.123e+06      0.129   7.07e+07      0.000    9.12e+06    9.12e+06
===================================================================================
Ljung-Box (Q):                       28.25   Jarque-Bera (JB):                14.73
Prob(Q):                              0.92   Prob(JB):                         0.00
Heteroskedasticity (H):               0.58   Skew:                            -0.14
Prob(H) (two-sided):                  0.04   Kurtosis:                         4.39
===================================================================================

Warnings:
[1] Covariance matrix calculated using the outer product of gradients (complex-step).
[2] Covariance matrix is singular or near-singular, with condition number 4.3e+23. Standard errors may be unstable.
"""
```

Looking again at your code, I think it's because you misspelled `exogenous` (you spelled it "exogeneous"). This doesn't get caught, because it is considered part of `**kwargs` and passed up to the statsmodels `fit` method. If they choose not to warn or raise, it will never get caught.

**Comment by tdesilvam** [comment]
Thank you.

**Comment by Anaisdg** [comment]
Thank you @tgsmith61591 !! Spelling...
