### ISSUE TITLE
Deviations from M4 published results

### ISSUE THREAD

**Issue by mloning** [alkaline-ml/pmdarima#310]
**Question**
I'm trying to replicate the ARIMA results published in the [M4 study](https://github.com/Mcompetitions/M4-methods), results look fairly good already, just a large deviation for the hourly series. 

| | Yearly | Quarterly | Monthly | Weekly | Daily | Hourly
-- | -- | -- | -- | -- | -- | --
AutoARIMA | 1.617091 | 3.101922 | 5.110317 | 0.851063 | -2.142316 | 82.225751
> Values are percentage difference between published sMAPE and replicated ones, i.e. a value of 100 means 100% difference, positive values indicate the replicated results are worse than published results. 

I believe they rely on R's auto-arima method, but cannot find the exact code they used. I've raised an [issue](https://github.com/Mcompetitions/M4-methods/issues/24) to find out more. 

Since I'm wrapping your `AutoARIMA` class, the error may well be on my side. I need to look into it in more depth, but wanted to ask whether you are aware of any difference with respect to R's version. May be related to seasonality.

**Comment by tgsmith61591** [comment]
@mloning is there any chance you can share your code? Or is it proprietary?

**Comment by mloning** [comment]
Quick update: I misspecified how the seasonality is handled, so after re-running it the large deviation for the Hourly dataset is gone. So I think I'll leave it at that for now. I'll add a link to the code once I've sorted out a few other things! But feel free to close the issue. 
 
| | Yearly | Quarterly | Monthly | Weekly | Daily | Hourly
| -- | -- | -- | -- | -- | -- | -- |
AutoARIMA | 1.617 | 4.572 | 2.418 | 0.851 | -2.142 | -2.017

**Comment by tgsmith61591** [comment]
That's a relief :-) Thanks for the follow-up.
