### ISSUE TITLE
Differencing as subtracting the previous observation from the current observation or vice versa?

### ISSUE THREAD

**Issue by ghuname** [alkaline-ml/pmdarima#311]
**Question**
Can you please explain whether differencing should be done as X(t-1) - X(t) [as pmdarima is doing] instead of X(t) - X(t-1). For example, on page: http://alkaline-ml.com/pmdarima/tips_and_tricks.html#understanding-differencing-d
there is a code:

```
x = c(10, 4, 2, 9, 34)

# 1
x_lag = x[1:]  # first lag
x = x_lag - x[:-1]  # first difference
# x = [ -6.,  -2.,   7.,  25.]

# 2
x_lag = x[1:]  # second lag
x = x_lag - x[:-1]
# x = [ 4.,  9., 18.]
```
in which you do `x = x_lag - x[:-1]` instead of `x = x[:-1] - x_lag`.
I don't say it is wrong, I am just asking for double check, because on many sites I have found the second approach:
1. https://machinelearningmastery.com/difference-time-series-dataset-python/  (difference(t) = observation(t) - observation(t-1))
2. https://otexts.com/fpp2/stationarity.html (chapter Second-order differencing)
3. https://nwfsc-timeseries.github.io/atsa-labs/sec-tslab-differencing-to-remove-a-trend-or-seasonal-effects.html
...

Can you please check?

**Comment by tgsmith61591** [comment]
pmdarima is not differencing via X(t-1) - X(t). I think your confusion is in the python slice notation, `X[:-1]` (which slices up to the second-to-last element).

```python
import pmdarima as pm

>>> x = pm.c(10, 4, 2, 9, 34)

# if this is t:
>>> x[1:]
array([ 4,  2,  9, 34])

# this is t - 1:
>>> x[:-1]

>>> so observation(t) - observation(t - 1):
>>> x[1:] - x[:-1]
array([-6, -2,  7, 25])
```

Incidentally, this is the same result you get from R:

```R
> x = c(10, 4, 2, 9, 34)
> diff(x)
[1] -6 -2  7 25
```

It would be invalid to difference forward, as it requires a priori knowledge of what comes next in the series, which we can't know at inference time.
