### ISSUE TITLE
using SARIMAX model for prediction

### ISSUE THREAD

**Issue by tdesilvam** [alkaline-ml/pmdarima#313]
I have trained a SARIMAX model using Jupyter notebook, pmdarima few weeks ago, and then closed the file. After reopen the file, can I directly use the trained SARIMAX model, which I already built? 
I tried to call the model, error says model cannot be identified.
"name 'smodel' is not defined"

 My worry is model training time is approximately 7 hours. Therefore I want to use the trained model.
Please see the codes and output of model given below.

smodel = pm.auto_arima(train, start_p=1, start_q=1,
                         test='adf',
                         max_p=3, max_q=3, m=24,
                         start_P=0, seasonal=True,
                         d=None, D=1, trace=True,
                         error_action='ignore',  
                         suppress_warnings=True, 
                         stepwise=True)

smodel.summary()

Output
![image](https://user-images.githubusercontent.com/55757721/77597100-69260980-6ec3-11ea-8c04-ab50ae6a5a50.png)

**Comment by tgsmith61591** [comment]
This is how you serialize, deserialize a model for later use:
https://alkaline-ml.com/pmdarima/auto_examples/arima/example_persisting_a_model.html#sphx-glr-auto-examples-arima-example-persisting-a-model-py

Once you have your model, you have to pickle it and then load it again later for re-use. If you killed your jupyter instance without saving the model, you won't be able to recover it.

```python
import pickle

# save
with open('mymodel.pkl', 'wb') as p:
    pickle.dump(smodel, p)

# load
with open('mymodel.pkl', 'rb') as p:
    smodel = pickle.load(p)
```

**Comment by tdesilvam** [comment]
One more clarification. I want to predict using my model using the function smodel.predict() for 72 periods. Can I do it separately 0:24, 24:48, 48:72 ? If yes, please show me how to do it? I know only smodel.predict(n_periods=72) and predict all the 72 periods at once.
