### ISSUE TITLE
programmatically checking `m`

### ISSUE THREAD

**Issue by novarac23** [alkaline-ml/pmdarima#321]
**Question**

Hi everyone 👋 

First of all thank you to everyone who made/is maintaining this library 🙌 It's been a life saver 🙏 

I'm not sure if this is actually possible (I couldn't find a solution after googling/going through issues)  but is there a way to check if a specific `m` will work for a specific dataset? 

In my use case a user provides a dataset and a value of `m` param and sometimes `m` that's being set just won't work. Is there a way to check in advance if `m` that's being set will work or not? 🤔

**Comment by tgsmith61591** [comment]
Hey there. There's not a _great_ solution to this. Typically `m` is an a priori term. We have a [brief section](http://alkaline-ml.com/pmdarima/tips_and_tricks.html#setting-m) on this in the documentation, and Rob Hyndman wrote a nice [blog post](https://robjhyndman.com/hyndsight/seasonal-periods/) on the subject.

That said, you could always do a crude grid search in a loop (make sure you use some of our [newer cross-validation](http://alkaline-ml.com/pmdarima/auto_examples/model_selection/example_cross_validation.html#sphx-glr-auto-examples-model-selection-example-cross-validation-py) methods), but there is no clever out-of-the-box method for this.

**Comment by novarac23** [comment]
Hi @tgsmith61591 👋 

Thank you for responding! Read the docs on pmdarima and that post, they were both really helpful. While digging through some stuff last night I realized most of the issues that I'm having come from the fact that `nsdiffs` fails, so checking for that should solve the problem!

I'll go ahead and close the issue! Thank you again for a response I really appreciate it! 🙏
