### ISSUE TITLE
Adding date dimension

### ISSUE THREAD

**Issue by srayagarwal** [alkaline-ml/pmdarima#328]
I have quarterly data, and my dates are as an index of the series.
in auto_arima, m=4 (as its quarterly data)
If in the series my date start with mid of the year (21-07-2013) or beginning of the year (21-01-2013), the results are the same. This shows that arima is not taking the start date into consideration.

**Comment by tgsmith61591** [comment]
The ARIMA model does not treat your index as semantically meaningful. We actually have introduced a new `DateFeaturizer` that creates exogenous dummy variables from dates that will be present in the next release (1.6.0). Here is an example from the [dev docs](http://alkaline-ml.com/pmdarima/develop/auto_examples/preprocessing/example_date_featurizer.html#sphx-glr-auto-examples-preprocessing-example-date-featurizer-py). Eventually you'll be able to do something like:

```python
date_feat = preprocessing.DateFeaturizer(
    column_name="date",  # the name of the date feature in the exog matrix
    with_day_of_week=True,
    with_day_of_month=True)

pipe = pipeline.Pipeline([
    ('date', date_feat),
    ('arima', arima.AutoARIMA(d=n_diffs,
                              trace=3,
                              stepwise=True,
                              suppress_warnings=True,
                              seasonal=False))
])

pipe.fit(y_train, X_train)
```

Where `X_train` contains your date column. This is present on master, but it's not in an official release yet. If you want to use it now, you'd have to build from source.

**Comment by aaronreidsmith** [comment]
This is out in the wild with the [1.6.0 release](https://github.com/alkaline-ml/pmdarima/releases/tag/v1.6.0)
