### ISSUE TITLE
'SARIMAX' Object has no attribute '_k_trend' when imported from a pickle file

### ISSUE THREAD

**Issue by CJMki** [alkaline-ml/pmdarima#332]
I have created a pipeline using following code 
`pipe = Pipeline([
    ('boxcox', BoxCoxEndogTransformer(lmbda2=1e-6)),
    ('arima', pmd.AutoARIMA(trace=True,
                           suppress_warnings=True,
                           m=12,
                           stepwise=True))
])`

and fitted it like this 
`fitted = pipe.fit(train)`
Afterwards I created a pickle dump (this part was done in google colabs, pmdarima-1.6.0)
Then I created a local application perform predictions locally, however I am getting this error 
`AttributeError: 'SARIMAX' object has no attribute '_k_trend'`
Can anyone explain me what have I done wrong here ?

**Comment by aaronreidsmith** [comment]
Do you have the same version of `statsmodels` installed both locally and on Google Colab? That appears to be a `statsmodels` error. Run one of the following from the command line to find out, and please paste the results here!

```bash
$ pip freeze
```

```bash
$ python -c "import pmdarima; pmdarima.show_versions()"
```

**Comment by CJMki** [comment]
from local run time
Python dependencies:
        pip: 19.0.3
 setuptools: 40.8.0
    sklearn: 0.22.2.post1
statsmodels: 0.11.1
      numpy: 1.18.4
      scipy: 1.4.1
     Cython: 0.29.17
     pandas: 1.0.3
     joblib: 0.14.1
   pmdarima: 1.6.0
-------------------------
from colab
Python dependencies:
        pip: 19.3.1
 setuptools: 46.1.3
    sklearn: 0.22.2.post1
statsmodels: 0.10.2
      numpy: 1.18.4
      scipy: 1.4.1
     Cython: 0.29.17
     pandas: 1.0.3
     joblib: 0.14.1
   pmdarima: 1.6.0

You were right, the statsmodels version is different, but both places I ran pip install pmdarima. How can it install two different versions for the same dependency ?

**Comment by aaronreidsmith** [comment]
We have a [minimum version of statsmodels](https://github.com/alkaline-ml/pmdarima/blob/2e4639579e47f20616f505e35e1c6c1dcd9a827c/requirements.txt#L7) we support, which is 0.10.2.  Running `!pip freeze` from a brand new Google Colab notebook shows it comes preinstalled with 0.10.2, so the pmdarima installer did not upgrade it. However, locally you likely didn’t have statsmodels, so the installer installed the latest version.

This is something that we need to put a compatibility function into pmdarima to avoid, but I _think_ a workaround should be to either upgrade statsmodels on Google Colab:

```
pip install --upgrade statsmodels
```

Or to downgrade locally:

```
pip install "statsmodels==0.10.2"
```

Let us know if either of those work, and we’ll get working on a compatibility fix in the meantime.

**Comment by CJMki** [comment]
Hi @aaronreidsmith , 

The later option worked and thank you for your help
