### ISSUE TITLE
How does auto_arima handle transformations of exogenous variables?

### ISSUE THREAD

**Issue by tlicquia** [alkaline-ml/pmdarima#345]
Hi,

I've looked through past issues and the source code for auto_arima and couldn't find a clear answer to this.  Will auto_arima explore any transformations of exogenous variables that are passed in to the function?  For example, if the best-fit model lands on ARIMA(1,1,1), can I expect that a first-order differencing was also applied to the X variable(s) as well?  Or would I need to manually difference my X variable(s) before passing them into auto_arima?  Aside from differencing, what about lags or other possible transformations?  Thank you!

**Comment by tgsmith61591** [comment]
You do not need to pre-difference your X variables. When you fit an ARIMA(1,1,1), the same differencing that's applied to your `y` will applied to the `X`. That actually takes place inside of the statsmodels code, which is why you didn't find a direct reference to it in our doc

**Comment by tlicquia** [comment]
Thank you for the clarification.
