### ISSUE TITLE
Checking for near non-invertible roots in auto_arima is subsequently ignored

### ISSUE THREAD

**Issue by msissons** [alkaline-ml/pmdarima#354]
**Describe the bug**
Checking for near non-invertible roots occurs in `_auto_solvers._root_test(model, ic, trace)` - this returns `np.inf` if the roots are near non-invertible. 

However, the return value from `_root_test` is only used to determine which model should be saved as `.bestfit` during a stepwise parameter search. The actual model IC remains unmodified and the model itself is stored in `.results_dict` for onward calculation. In the non-stepwise approach, this test is not performed at all.

Once the parameter search has finished, all the results are fitltered for None in `auto._post_ppc_arima` and then sorted according to the IC. Assuming only one model is required, `auto._return_wrapper` returns the value at the top of the list. The root testing is therefore ignored as the only possible effect it can have is on the model stored in `.bestfit`, which is not used outside the stepwise calculation.

In the R version of the code, it appears that the root testing modifies the IC of the actual model (setting it to Inf) and therefore the model will be ignored in subsequent calculations.

**To Reproduce**  
Run a stepwise parameter search, where the model with the lowest AIC has near non-invertible roots

**Versions**
Darwin-18.7.0-x86_64-i386-64bit
Python 3.7.4 (default, Oct 12 2019, 18:55:28) 
[Clang 11.0.0 (clang-1100.0.33.8)]
pmdarima 1.5.3
NumPy 1.18.2
SciPy 1.4.1
Scikit-Learn 0.22.2.post1
Statsmodels 0.11.1

**Expected behavior**
All models with near non-invertible roots should be discarded. Of the remaining models, the model with the lowest AIC should be selected

**Actual behavior**
The model with the lowest AIC is selected, regardless of whether the roots are near non-invertible

**Additional context**
Having a quick look at the R code, it seems that the root testing modifies the IC of the model itself, which would avoid this issue occurring ( https://github.com/robjhyndman/forecast/blob/master/R/newarima2.R#L780 )

Incidentally, the final model order on the stepwise search is reported from the `.bestfit` paramater of the model ( https://github.com/alkaline-ml/pmdarima/blob/master/pmdarima/arima/_auto_solvers.py#L342 ) but this may not reflect the final values selected.

**Comment by tgsmith61591** [comment]
Good catch, thank you for bringing this to our attention

**Comment by tgsmith61591** [comment]
The fix for this will be included in the next (1.7.0) release.
