### ISSUE TITLE
ModuleNotFoundError: No module named 'sklearn.externals.joblib'

### ISSUE THREAD

**Issue by E-B-Manohar** [alkaline-ml/pmdarima#355]
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-23-1f512963c620> in <module>()
      2 import sys
      3 sys.modules['sklearn.externals.six'] = six
----> 4 import pmdarima as pm

C:\Anaconda3\lib\site-packages\pmdarima\__init__.py in <module>()
     27 
     28     # Stuff we want at top-level
---> 29     from .arima import auto_arima, ARIMA, AutoARIMA
     30     from .utils import acf, autocorr_plot, c, pacf, plot_acf, plot_pacf
     31 

C:\Anaconda3\lib\site-packages\pmdarima\arima\__init__.py in <module>()
      5 from .approx import *
      6 from .arima import *
----> 7 from .auto import *
      8 from .utils import *
      9 from .warnings import *

C:\Anaconda3\lib\site-packages\pmdarima\arima\auto.py in <module>()
      9 from sklearn.utils.validation import check_array, column_or_1d, check_is_fitted
     10 from sklearn.utils import check_random_state
---> 11 from sklearn.externals.joblib import Parallel, delayed
     12 from sklearn.linear_model import LinearRegression
     13 

ModuleNotFoundError: No module named 'sklearn.externals.joblib'

**Comment by aaronreidsmith** [comment]
This looks like a duplicate of #147, which was fixed about a year ago. What version of `pmdarima` are you running?

Seeing as you are using conda, I am worried you may have an [unofficial release](https://anaconda.org/saravji/pmdarima), which is version 1.2.0. We have been working to get official conda support (see #326), but it is not out yet. The preferred way to install `pmdarima` on conda is `pip install pmdarima` to make sure you get the latest official release

**Comment by E-B-Manohar** [comment]
What version of pmdarima are you running? Answer: I've used "conda install -c saravji pmdarima" and yes it is 1.2.0
Oh, I had to downgrade sklearn to 0.20 to make this work.

**Comment by tgsmith61591** [comment]
@E-B-Manohar I'll reiterate what @aaronreidsmith said. `saravji` is unrelated to the project and uploaded an old version of the package to his conda channel. I would be careful about using third-party versions like that. The public package is on 1.6.1; it would be best to use `pip install pmdarima` to stay up-to-date with the current version.

**Comment by E-B-Manohar** [comment]
> @E-B-Manohar I'll reiterate what @aaronreidsmith said. `saravji` is unrelated to the project and uploaded an old version of the package to his conda channel. I would be careful about using third-party versions like that. The public package is on 1.6.1; it would be best to use `pip install pmdarima` to stay up-to-date with the current version.

Thanks for the Heads Up; will follow the best method mentioned

**Comment by mk-sudo** [comment]
Solved the issue with below code

```
import six
import sys
sys.modules['sklearn.externals.six'] = six
import mlrose
import joblib
sys.modules['sklearn.externals.joblib'] = joblib
```
