### ISSUE TITLE
In-sample predictions vary significantly from train set

### ISSUE THREAD

**Issue by juandavidlozano** [alkaline-ml/pmdarima#362]
Hi, I am starting to use your library, but I dont know if this is a bug or maybe you can help me to see what is wrong.  I have used this data set on other forecasting packages in R (fpp3, forecast, etc) and I was looking one that would do an auto arima and I found yours,  I am running to this issue that for some reason with the data that I am using at the end of the forecast the forecast values go to the negative, I have checked the file for errors but I dont find any, and its also the same file I use with R and it gives correct results.

thanks

I am sending you a jupiter notebook and dataset I am using.
[forecast in python.zip](https://github.com/alkaline-ml/pmdarima/files/4922279/forecast.in.python.zip)

at the beginning of the notebook I am practicing with the datasets provided in the library if you down a little more you can see when I use my data and the issue in the graph

**Comment by tgsmith61591** [comment]
Hi @juandavidlozano, it's helpful to the maintainers and any future users with a similar issue if you include code snippets in your issue. Most folks will not download the zip to sift through it. Would you mind including a concise, reproducible snippet of the call to `auto_arima` (both in pmdarima and in R so I can compare)?

**Comment by juandavidlozano** [comment]
this is the code that works with R

```
options(scipen=999)
library(fpp3)
data <- read.csv(file = 'maurice_covid_daily1.csv')
data$DateFinal <- as.Date(data$DateFinal, "%m/%d/%Y")
t_data <- as_tsibble(data, index = DateFinal)

fit.cons1 <- t_data %>%
  model(
    tslm = TSLM(Total_Revenue ~ Total_NetSpend +covid_deaths +Unemployment+CPI +covid_cases+VIX +SPY )
  )

report(fit.cons1)

fit.cons2 <- t_data %>%
  model(
    tslm = TSLM(Total_Revenue ~ Total_NetSpend +covid_deaths +Unemployment+CPI +covid_cases+VIX +SPY +trend() + season() )
  )

report(fit.cons2)

fit.cons3 <- t_data %>%
  model(
    tslm = ARIMA(Total_Revenue ~ Total_NetSpend +covid_deaths +Unemployment+CPI +covid_cases+VIX +SPY )
  )



report(fit.cons3)

augment(fit.cons1) %>%
  ggplot(aes(x = DateFinal)) +
  geom_line(aes(y = Total_Revenue, colour = "Data")) +
  geom_line(aes(y = .fitted, colour = "Fitted"))


augment(fit.cons2) %>%
  ggplot(aes(x = DateFinal)) +
  geom_line(aes(y = Total_Revenue, colour = "Data")) +
  geom_line(aes(y = .fitted, colour = "Fitted"))

augment(fit.cons3) %>%
  ggplot(aes(x = DateFinal)) +
  geom_line(aes(y = Total_Revenue, colour = "Data")) +
  geom_line(aes(y = .fitted, colour = "Fitted"))

accuracy(fit.cons1)
accuracy(fit.cons2)
accuracy(fit.cons3)
```
on that code I have 3 models, a TSLM, a TSLM with trend and season, and an ARIMA, they all work and you can see the graphs

![Capture2](https://user-images.githubusercontent.com/26095551/87502323-4ca70c00-c62f-11ea-9fab-933ccbc25003.GIF)


this is the code for Python

```
import numpy as np
import pandas as pd
from pmdarima.arima import auto_arima

data1=pd.read_csv('maurice_covid_daily1.csv')
data2 = data1.values
train, test = model_selection.train_test_split(data2, train_size=850)
arima = auto_arima(train[:,1], exogenous=train[:,2:8], suppress_warnings=True,
                   stationarity=False, seasonality=True)
arima.summary()
predictions = arima.predict(n_periods=train.shape[0], exogenous=train[:,2:8])

plt.plot(train[:,1], c='blue')
plt.plot(predictions, c='green')
```

![Capture](https://user-images.githubusercontent.com/26095551/87502259-24b7a880-c62f-11ea-9beb-a30e58502aca.GIF)

**Comment by tgsmith61591** [comment]
Thanks for the added info 👍  There are a couple things that are a little bit off. I made some changes in your code with comments:

```python
import numpy as np
import pandas as pd
import pmdarima as pm
from matplotlib import pyplot as plt

data1 = pd.read_csv('maurice_covid_daily1.csv')
data2 = data1.values

train, test = pm.model_selection.train_test_split(data2, train_size=850)
arima = pm.auto_arima(train[:,1],
                      exogenous=train[:,2:8],
                      suppress_warnings=True,
                      seasonal=False,  # this doesn't appear to be seasonal
                      trace=1)

# to get forecasts on the test set, use `predict`
forecasts = arima.predict(n_periods=test.shape[0], exogenous=test[:,2:8])
# to get predictions on the in-sample series, use `predict_in_sample`
pred_in_sample = arima.predict_in_sample(n_periods=train.shape[0],
                                         exogenous=train[:,2:8])

# Plotting
fig = plt.figure(figsize=(18, 8))

x_train = np.arange(train.shape[0])
x_test = np.arange(test.shape[0]) + train.shape[0]

plt.plot(x_train, train[:,1], c='blue', label='train')
plt.plot(x_train, pred_in_sample, c='red', label='train-preds')
plt.plot(x_test, forecasts, c='green', label='test-preds')
plt.legend(loc='lower right')

plt.show()
```

Here's what I get:

<img width="1243" alt="Screen Shot 2020-07-15 at 7 38 57 AM" src="https://user-images.githubusercontent.com/6124706/87545984-70d60d80-c66e-11ea-9b00-53cf0e70e08e.png">

Note that I ran this on the dev version of master which contains a couple changes since v1.6.1, so it might differ slightly but you should get similar results when you run the code above.

**Comment by tgsmith61591** [comment]
Did this solve your issue, @juandavidlozano ? If so, I will close out the issue.

**Comment by juandavidlozano** [comment]
HI, sorry for the delay

do you know why when I use your code but I change the size of the of the test sample I run into that issue (the negative values)

code 

```
import numpy as np
import pandas as pd
import pmdarima as pm
from matplotlib import pyplot as plt
from pmdarima import model_selection

data1 = pd.read_csv('maurice_covid_daily1.csv')
data2 = data1.values

train, test = pm.model_selection.train_test_split(data2, train_size=700)
arima = pm.auto_arima(train[:,1],
                      exogenous=train[:,2:8],
                      suppress_warnings=True,
                      seasonal=False,  # this doesn't appear to be seasonal
                      trace=1)

# to get forecasts on the test set, use `predict`
forecasts = arima.predict(n_periods=test.shape[0], exogenous=test[:,2:8])
# to get predictions on the in-sample series, use `predict_in_sample`
pred_in_sample = arima.predict_in_sample(n_periods=train.shape[0],
                                         exogenous=train[:,2:8])

# Plotting
fig = plt.figure(figsize=(18, 8))

x_train = np.arange(train.shape[0])
x_test = np.arange(test.shape[0]) + train.shape[0]

plt.plot(x_train, train[:,1], c='blue', label='train')
plt.plot(x_train, pred_in_sample, c='red', label='train-preds')
plt.plot(x_test, forecasts, c='green', label='test-preds')
plt.legend(loc='lower right')

plt.show()
```

![Capture5](https://user-images.githubusercontent.com/26095551/88197733-df880d80-cc10-11ea-83c4-9018da727e29.GIF)

**Comment by juandavidlozano** [comment]
Nevermind I think I was able to figure it out.
