### ISSUE TITLE
Cross_val_predict: enable returning predictions for different horizons.

### ISSUE THREAD

**Issue by tuomijal** [alkaline-ml/pmdarima#364]
# Cross_val_predict: enable returning predictions for different horizons

I wonder if we should modify `cross_val_predict` so that it return a matrix of predictions indexed by DatetimeIndex and containing horizonwise results in columns.

## Problem
Currently `cross_val_predict` averages predictions of overlapping folds. For example, consider the case provided in [examples](http://alkaline-ml.com/pmdarima/modules/generated/pmdarima.model_selection.cross_val_predict.html#pmdarima.model_selection.cross_val_predict) with minor modifications:

```python
import pmdarima as pm
from pmdarima.model_selection import cross_val_predict, RollingForecastCV

# http://alkaline-ml.com/pmdarima/modules/generated/pmdarima.model_selection.cross_val_predict.html#pmdarima.model_selection.cross_val_predict
y = pm.datasets.load_wineind()
cv = RollingForecastCV(h=14, step=12)
preds = cross_val_predict(pm.ARIMA((1, 1, 2), 
                                   seasonal_order=(0, 1, 1, 12), 
                                   suppress_warnings=True), 
                          y, 
                          cv=cv)
```

```python
import pandas as pd
y = pd.Series(y)
y_pred = pd.Series(preds, index=y.index[-preds.shape[0]:])
y.plot();
y_pred.plot();
```

![output_3_0](https://user-images.githubusercontent.com/23170686/87942848-dfb7ca00-caa5-11ea-9395-02a210c405bf.png)

Currently the API returns a vector no matter how greatly folds overlap. In the above case this does not matter greatly since the overlap is relatively rare. 

However, if we were to perform an exhaustive iteration e.g. with horizon of 30 days (h=30) and step of 1  day (step=1) we would end up with significant overlap. Averaging over these results is often not the desired approach. Instead we often want to evaluate the predictive accuracy on different horizons. Like so:

| horizon (days)| accuracy |
| -------       | -------- |
| 1             |  5       |
| 2             |  6       |
| 3             |  7       |
| n             |  x       |

## Proposed solution
Getting these kind of metrics would be simple if `cross_val_predict` returned something like:

| DateTime    | t+1      | t+2     | t+3    | t+h   |
| --------    | ------ | ----- | ---- | --- |
| 01-01-1917  | 20     | 25    | 18   | p1  |
| 02-01-1917  | 13     | 17    | 29   | p2  |
| 03-01-1917  | 19     | 14    | 18   | p3  |
| ...          |   |   |   |   |

,where `t` is the forecast origin, `h` is horizon and `t+h` is naturally prediction for `h` days from `t`. E.g. in the above case we predict on January 1st of 1917 that the target variable will be 25 on January 3rd.

Looking at the source code it seems to me this wouldn't be a huge modification since a similiar matrix is calculated prior averaging. 

## Conclusion

I believe this would be of significant value because step=1 is a specially important case of crossvalidation. I am happy to help in any way possible in case @tgsmith61591 and @aaronreidsmith  feel this is a feature worth implementing. Again, thank you in advance for your input and keep up the excellent work!

**Comment by tgsmith61591** [comment]
I think this is a really good idea. Here are a couple thoughts

* Changing the default behavior of the existing function is probably not desirable, since there could be nasty surprises for anyone using `cross_val_predict`. We'd probably want a default kwarg `return_forecast_horizons=False` (or something similar) that would behave like this when True, and let users do their own averaging on the returned matrix.
* (More minor) I am not sure indexing on datetime can always be guaranteed, since a raw numpy array is valid `y` input. It might make sense to just return the raw 2D array, but I think that matters less

Is this something you'd be willling to take on?

**Comment by tuomijal** [comment]
Thank you for swift reply and ideas! I would be more than happy to take responsibility on this but please note that I am not a software engineer meaning this will be a learning experience and I can make little guarantees on code quality. But I will be more than happy to submit a draft for you to assess.

**Comment by aaronreidsmith** [comment]
We don't bite 🙂 Just trying to build the community! We can help if you get stuck; [here is our contributing guide](http://alkaline-ml.com/pmdarima/contributing.html#contrib) to get started!

**Comment by tuomijal** [comment]
I started looking into this. I can't wrap my head around one issue. 

```python
print(__doc__)

# Author: Taylor Smith <taylor.smith@alkaline-ml.com>
# http://alkaline-ml.com/pmdarima/auto_examples/model_selection/example_cross_val_predict.html#sphx-glr-auto-examples-model-selection-example-cross-val-predict-py

import numpy as np
import pmdarima as pm
from pmdarima import model_selection
from matplotlib import pyplot as plt

print("pmdarima version: %s" % pm.__version__)

# Load the data and split it into separate pieces
y = pm.datasets.load_wineind()
# Limit to first 100 for simplicity
y = y[:100]

est = pm.ARIMA(order=(1, 1, 2),
               seasonal_order=(0, 1, 1, 12),
               suppress_warnings=True)
cv = model_selection.SlidingWindowForecastCV(window_size=90, step=1, h=4)

predictions = model_selection.cross_val_predict(
    est, y, cv=cv, verbose=2, averaging="median", return_forecast_horizons=True)


>>>Automatically created module for IPython interactive environment
>>>pmdarima version: 0.0.0
>>>[CV] fold=0 ..........................................................
>>>[CV] fold=1 ..........................................................
>>>[CV] fold=2 ..........................................................
>>>[CV] fold=3 ..........................................................
>>>[CV] fold=4 ..........................................................
>>>[CV] fold=5 ..........................................................
```

We have 100 samples, window of 90 and horizon of 4 but we get 6 folds. Wouldn't we actually expect to have 7 folds? Like this:

![Screenshot 2020-07-25 at 16 44 02](https://user-images.githubusercontent.com/23170686/88458355-1d499800-ce96-11ea-9ed8-b065c2520d55.png)

What I am not getting?

**Comment by tgsmith61591** [comment]
Hey this is a really good question. The culprit seems to be [this point in the code](https://github.com/alkaline-ml/pmdarima/blob/master/pmdarima/model_selection/_split.py#L332):

```python
        indices = np.arange(n_samples)
        for window_start in range(0, n_samples - h - window_size, step):
            window_end = window_start + window_size
            train_indices = indices[window_start: window_end]
            test_indices = indices[window_end: window_end + h]
            yield train_indices, test_indices
```

Which in this case essentially creates `range(0, 6, 1)`. I bet we could create that loop a bit more intelligently, this is a true bug. Great catch

**Comment by tgsmith61591** [comment]
Try again @tuomijal should be fixed on master

**Comment by tuomijal** [comment]
Works like a charm, thank you!

**Comment by tgsmith61591** [comment]
Dang, must have missed that in the other fix.
