### ISSUE TITLE
Allow custom scoring function for ARIMA() and AutoARIMA()

### ISSUE THREAD

**Issue by Seirdy** [alkaline-ml/pmdarima#368]
Currently, AutoARIMA optimizes ARIMA to achieve the lowest score according to its "scoring" parameter. This parameter can specify either mean-squared error or mean-absolute error. It would be extremely helpful to specify other error metrics from `sklearn.metrics`, or pass to arbitrary callables that take similar kwargs. This could allow greater flexibility for customizing the optimization than specifying sample weights in `scoring_args`.

**Comment by tgsmith61591** [comment]
I think this makes sense. Thanks for the suggestion!

**Comment by tgsmith61591** [comment]
This will be released in 1.7.0 soon
