### ISSUE TITLE
seasonal_order does not accept iterable PDQ parameters

### ISSUE THREAD

**Issue by brianseodd** [alkaline-ml/pmdarima#370]
**Describe the bug**
Cannot pass an iterable to kwarg=season_order in pm.ARIMA

**To Reproduce**  

```python
import pmarima as pm
m = pm.ARIMA(order=(2, 1, 2), seasonal_order=([1, 2, 3, 52], 0, 1, 7))
m.fit(range(2000))
```

**Versions**
System:
    python: 3.7.6 (default, Dec 30 2019, 19:38:28)  [Clang 11.0.0 (clang-1100.0.33.16)]
executable: /usr/local/opt/python/bin/python3.7
   machine: Darwin-19.6.0-x86_64-i386-64bit

Python dependencies:
        pip: 20.2
 setuptools: 42.0.2
    sklearn: 0.23.1
statsmodels: 0.11.1
      numpy: 1.18.1
      scipy: 1.4.1
     Cython: 0.29.17
     pandas: 0.25.3
     joblib: 0.14.1
   pmdarima: 1.6.1

**Expected behavior**
This should create a seasonal order with lags of 1,2,3,52 but it is failing on validation to check whether the model parameters include a seasonal order

**Actual behavior**
/usr/local/lib/python3.7/site-packages/pmdarima/compat/statsmodels.py in check_seasonal_order(order)
     46         The existing seasonal order
     47     """
---> 48     if sum(order[:3]) == 0 and order[-1] == 1:
     49         order = (0, 0, 0, 0)
     50 

TypeError: unsupported operand type(s) for +: 'int' and 'list'

**Additional context**
Works fine when using iterables in the order kwarg but not in the seasonal_order kwarg

**Comment by tgsmith61591** [comment]
This has never been supported. What is the intended behavior? That it would try all of them and select the best?

**Comment by brianseodd** [comment]
@tgsmith61591  it's supported as part of the statsmodel SARIMAX in the API. This doesn't apply to the auto arima API unless the random search option is changed. 

When using order=(3,1,0) you get 3 AR terms, AR1,2,3. Whereas if you do order=([3],1,0) statsmodels returns only AR,3. The notation works fine for `order` in pm.ARIMA but `seasonal_order` has an extra check that prevents the parameter from being passed through correctly. When I manually disable the validation function, it gets passed to the pm.arima -> SARIMAX correctly.

**Comment by tgsmith61591** [comment]
Gotcha. More than happy to accept a PR!
