### ISSUE TITLE
multivariate  categorical  time series predictions

### ISSUE THREAD

**Issue by Sandy4321** [alkaline-ml/pmdarima#374]
**Is your feature request related to a problem? Please describe.**
your package was admired  here 
https://machinelearningmastery.com/xgboost-for-time-series-forecasting/

pls see below, can you add multivariate time series predictions
especially for mix of categorical and continues features or at leas for categorical  time series predictions

Rahul Kalluri August 6, 2020 at 7:15 am #
This article doesn’t make a cogent argument for using XGBoost for time-series or time dependent data.

Without any sort of weighting based on time, the algorithm has no way of knowing how to incorporate time – it just looks at isolated points e.g. A yields 400, B yields 510 with no chronological relationship between A and B. The expected vs predicted graph you show clearly indicates that the model fails to establish a proper relationship between time and predictions.

I’ve tried to implement XGBoost in financial forecasting with 2 years historical data, it just doesn’t work well. Sometimes you can get better accuracies with ensembling techniques, but nothing really beats a true time series model. In that case, I’d use the pmdarima package and the auto.arima function is fantastic.

I get that you could use this as an example template, but I think it’s not really instructional until you measure this against a time-series model or apply some sort of time weights to non-time series models to get a clear idea of what options exist.

At worst, this article is misleading. At best, it’s flawed and requires more testing and examples.

I appreciate you putting this out there because it brings up some good questions on how to approach time series problems with some more flexibility, I’d look forward to a more thorough article on this topic.

**Comment by tgsmith61591** [comment]
> can you add multivariate time series predictions
especially for mix of categorical and continues features or at leas for categorical time series predictions

This seems like a couple questions. We support exogenous regressors, and for categorical regressors you could always create a dummy matrix of features. Categorical predictions are not currently supported

**Comment by tgsmith61591** [comment]
@Sandy4321 Do the existing categorical regressor approaches solve your problem?

**Comment by Sandy4321** [comment]
https://github.com/tgsmith61591  Do the existing categorical regressor approaches solve your problem?

did not find one
do  you know code solutions for categorical regressor

**Comment by tgsmith61591** [comment]
As I said:
> We support exogenous regressors, and for categorical regressors you could always create a dummy matrix of features

One-hot encode your exogenous features.
