### ISSUE TITLE
cannot import name 'six' from 'sklearn.externals' (/opt/anaconda3/lib/python3.7/site-packages/sklearn/externals/__init__.py)

### ISSUE THREAD

**Issue by naghmeh6** [alkaline-ml/pmdarima#375]
It has been 2 days that I am trying to import pmdarima. But I can not I keep getting this error:

 `cannot import name 'six' from 'sklearn.externals' (/opt/anaconda3/lib/python3.7/site-packages/sklearn/externals/__init__.py)`

I imported six separately but nothing changed. I am using Mac .os64, in Jupyter Notebook python 3.7

**Comment by aaronreidsmith** [comment]
Seems related to #355. Please be sure to search our closed issues and fill out the entire issue template next time you open an issue! 

A couple questions:
- What version of pmdarima are you trying to import? 
- Are you using Conda?

If you are using Conda, stop. The release that is published to Conda is **not** official or supported by us; someone took the code for version 1.2.0 and published it themselves.

The _only_ supported way to install pmdarima is `pip install pmdarima`. Give that a shot, and let us know if you still see that error.

**Comment by aaronreidsmith** [comment]
Just realized your issue title indicates you _are_ using Conda. Try `pip` and you should be good.

**Comment by naghmeh6** [comment]
in the environment of my conda I opened terminal and typed ` pip install pmdarima` it was successfully installed but same problem.

**Comment by naghmeh6** [comment]
God... thanks it working now!

**Comment by harmbuisman** [comment]
> Seems related to #355. Please be sure to search our closed issues and fill out the entire issue template next time you open an issue!
> 
> A couple questions:
> 
> * What version of pmdarima are you trying to import?
> * Are you using Conda?
> 
> If you are using Conda, stop. The release that is published to Conda is **not** official or supported by us; someone took the code for version 1.2.0 and published it themselves.
> 
> The _only_ supported way to install pmdarima is `pip install pmdarima`. Give that a shot, and let us know if you still see that error.
> 
> To clarify, you can use `pip` in a Conda environment. Just don't use `conda install -c saravji pmdarima`.

I ran into the same problem as the topic starter. Any chance you can release the latest version there as well or have the unofficial one removed?

**Comment by aaronreidsmith** [comment]
> Any chance you can release the latest version there as well

We have requested help on #326, but none of us are conda experts and cannot get it working properly. If you, or someone you know, has experience with conda, we are more than happy to accept PRs both here and in [pmdarima-conda](https://github.com/alkaline-ml/pmdarima-conda).

> or have the unofficial one removed?

We cannot remove the unofficial version as the publisher is not affiliated with us; it is within his rights as part of our [license](https://github.com/alkaline-ml/pmdarima/blob/master/LICENSE) to republish.
