### ISSUE TITLE
Python 3.9 support

### ISSUE THREAD

**Issue by aaronreidsmith** [alkaline-ml/pmdarima#389]
[Python 3.9 was released 2020-10-06](https://docs.python.org/3.9/whatsnew/3.9.html). We cannot build for Python 3.9 yet, as we are waiting on our upstream dependencies to release 3.9 builds, but I wanted to get ahead of the curve and open this issue for anyone looking for 3.9 support.

**Comment by slaughtering** [comment]
looking forward to the merge

**Comment by mprosperi** [comment]
me too
