### ISSUE TITLE
ImportError: cannot import name 'iterkeys'

### ISSUE THREAD

**Issue by anindya5** [alkaline-ml/pmdarima#390]
from pmdarima.arima import auto_arima

pmdarima only installed statsmodels 0.11.1

This code creates the error

ImportError Traceback (most recent call last)
in
4 import pickle
5 import numpy as np
----> 6 from pmdarima.arima import auto_arima

~/anaconda3/envs/local_env_wow_t4/lib/python3.6/site-packages/pmdarima/init.py in
49
50 # Stuff we want at top-level
---> 51 from .arima import auto_arima, ARIMA, AutoARIMA, StepwiseContext, decompose
52 from .utils import acf, autocorr_plot, c, pacf, plot_acf, plot_pacf,
53 tsdisplay

~/anaconda3/envs/local_env_wow_t4/lib/python3.6/site-packages/pmdarima/arima/init.py in
4
5 from .approx import *
----> 6 from .arima import *
7 from .auto import *
8 from .utils import *

~/anaconda3/envs/local_env_wow_t4/lib/python3.6/site-packages/pmdarima/arima/arima.py in
9 from sklearn.utils.validation import check_array
10
---> 11 from statsmodels import api as sm
12
13 from scipy.stats import gaussian_kde, norm

~/anaconda3/envs/local_env_wow_t4/lib/python3.6/site-packages/statsmodels/api.py in
12 from .regression.quantile_regression import QuantReg
13 from .regression.mixed_linear_model import MixedLM
---> 14 from .genmod import api as genmod
15 from .genmod.api import (GLM, GEE, OrdinalGEE, NominalGEE, families,
16 cov_struct,

~/anaconda3/envs/local_env_wow_t4/lib/python3.6/site-packages/statsmodels/genmod/api.py in
5 ]
6 from .generalized_linear_model import GLM
----> 7 from .generalized_estimating_equations import GEE, OrdinalGEE, NominalGEE
8 from .bayes_mixed_glm import BinomialBayesMixedGLM, PoissonBayesMixedGLM
9 from . import families

~/anaconda3/envs/local_env_wow_t4/lib/python3.6/site-packages/statsmodels/genmod/generalized_estimating_equations.py in
39 from statsmodels.genmod import families
40 from statsmodels.genmod.generalized_linear_model import GLM
---> 41 from statsmodels.genmod import cov_struct as cov_structs
42
43 import statsmodels.genmod.families.varfuncs as varfuncs

~/anaconda3/envs/local_env_wow_t4/lib/python3.6/site-packages/statsmodels/genmod/cov_struct.py in
7 http://www.stata.com/manuals13/xtxtgee.pdf
8 """
----> 9 from statsmodels.compat.python import iterkeys, itervalues
10 from statsmodels.compat.pandas import Appender
11

ImportError: cannot import name 'iterkeys'

**Comment by aaronreidsmith** [comment]
> pmdarima only installed statsmodels 0.11.1

That is the expected behavior. We currently [do not support 0.12](https://github.com/alkaline-ml/pmdarima/blob/d6678205e19d1dbf1b0e05db089fc87acc4dac96/requirements.txt#L7).

Your trace back implies that you have 0.12 installed, as iterkeys [is there](https://github.com/statsmodels/statsmodels/blob/9d94d96f253fef94a89113cddd32df69f9a8c4dc/statsmodels/compat/python.py#L52) in version 0.11, but [was removed in 0.12](https://github.com/statsmodels/statsmodels/blob/maintenance/0.12.x/statsmodels/compat/python.py).

Could you run `pip freeze` and paste the output here to confirm?

**Comment by aaronreidsmith** [comment]
Going to close this, as we haven't heard back in a week.
