### ISSUE TITLE
Is there a way to automatically access pmdarima's hyperparameter recommendations?

### ISSUE THREAD

**Issue by dkent603** [alkaline-ml/pmdarima#393]
I am building time series models using the statsmodels and pmdarima libraries. I have about 100 forecasts to run every 2 weeks.

I am using pmdarima for hyperparameter selection.

Is there a way to automatically access pmdarima's hyperparameter recommendations (i.e. without having to copy them manually based on the output of results.summary())?

**Comment by tgsmith61591** [comment]
Is this what you're after?

```python
In [1]: import pmdarima as pm

In [2]: y = pm.datasets.load_wineind()

In [3]: model = pm.auto_arima(y, m=12, suppress_warnings=True, trace=0)

In [4]: model.order
Out[4]: (1, 1, 2)

In [5]: model.seasonal_order
Out[5]: (0, 1, 1, 12)
```

**Comment by dkent603** [comment]
Yes - exactly.  Many thanks.
