### ISSUE TITLE
using pmdarima i'm getting NaN prediction.

### ISSUE THREAD

**Issue by david686** [alkaline-ml/pmdarima#397]
Hi everyone,

I'm trying to make prediction on some data.
![image](https://user-images.githubusercontent.com/57856270/98111745-c0ed1000-1ea9-11eb-9ec4-cd00f40b6ebb.png)

but for a reason that i don't understand i am getting NaN for prediction.
first i think that pm.auto_arima didn't like the type of the data.
but after some checks this not seems to be the reason.

Between checks when i simply replace the d parameter from None to 2 it work and gave me a good prediction(1 didn't work).

Maybe someone have been in the same situation and find the solution.

**Comment by tgsmith61591** [comment]
Can you share your data?

**Comment by david686** [comment]
Here the data
[pmd_arima - pmd_arima.zip](https://github.com/alkaline-ml/pmdarima/files/5487793/pmd_arima.-.pmd_arima.zip)
Thks

**Comment by david686** [comment]
Hey , is there any update !
it would be very helpful

**Comment by tgsmith61591** [comment]
Have not gotten a chance to look at this, sorry. I have been swamped at my day job this week; hope to look later

**Comment by tgsmith61591** [comment]
With no changes to your data, so far I am not able to replicate this. See below:

```python
In [10]: x = pd.read_csv(csv_path, header=None)

In [11]: model = pm.auto_arima(x, test='adf', trace=3, suppress_warnings=True, max_p=8, max_q=8)
Performing stepwise search to minimize aic
 ARIMA(2,1,2)(0,0,0)[0] intercept   : AIC=4353.086, Time=0.10 sec
First viable model found (4353.086)
 ARIMA(0,1,0)(0,0,0)[0] intercept   : AIC=4497.923, Time=0.01 sec
 ARIMA(1,1,0)(0,0,0)[0] intercept   : AIC=4490.596, Time=0.02 sec
 ARIMA(0,1,1)(0,0,0)[0] intercept   : AIC=4416.600, Time=0.02 sec
 ARIMA(0,1,0)(0,0,0)[0]             : AIC=4495.927, Time=0.01 sec
Near non-invertible roots for order (1, 1, 2)(0, 0, 0, 0); setting score to inf (at least one inverse root too close to the border of the unit circle: 1.000)
 ARIMA(1,1,2)(0,0,0)[0] intercept   : AIC=inf, Time=0.16 sec
 ARIMA(2,1,1)(0,0,0)[0] intercept   : AIC=4374.778, Time=0.08 sec
 ARIMA(3,1,2)(0,0,0)[0] intercept   : AIC=4328.129, Time=0.12 sec
New best model found (4328.129 < 4353.086)
 ARIMA(3,1,1)(0,0,0)[0] intercept   : AIC=4327.988, Time=0.08 sec
New best model found (4327.988 < 4328.129)
 ARIMA(3,1,0)(0,0,0)[0] intercept   : AIC=4351.070, Time=0.05 sec
 ARIMA(4,1,1)(0,0,0)[0] intercept   : AIC=4327.788, Time=0.29 sec
New best model found (4327.788 < 4327.988)
 ARIMA(4,1,0)(0,0,0)[0] intercept   : AIC=4335.900, Time=0.07 sec
 ARIMA(5,1,1)(0,0,0)[0] intercept   : AIC=4330.803, Time=0.16 sec
 ARIMA(4,1,2)(0,0,0)[0] intercept   : AIC=4330.275, Time=0.17 sec
 ARIMA(5,1,0)(0,0,0)[0] intercept   : AIC=4332.489, Time=0.15 sec
Near non-invertible roots for order (5, 1, 2)(0, 0, 0, 0); setting score to inf (at least one inverse root too close to the border of the unit circle: 0.995)
 ARIMA(5,1,2)(0,0,0)[0] intercept   : AIC=inf, Time=0.56 sec
 ARIMA(4,1,1)(0,0,0)[0]             : AIC=4326.990, Time=0.13 sec
New best model found (4326.990 < 4327.788)
 ARIMA(3,1,1)(0,0,0)[0]             : AIC=4327.486, Time=0.07 sec
 ARIMA(4,1,0)(0,0,0)[0]             : AIC=4334.628, Time=0.05 sec
 ARIMA(5,1,1)(0,0,0)[0]             : AIC=4328.283, Time=0.17 sec
 ARIMA(4,1,2)(0,0,0)[0]             : AIC=4328.751, Time=0.24 sec
 ARIMA(3,1,0)(0,0,0)[0]             : AIC=4349.395, Time=0.04 sec
 ARIMA(3,1,2)(0,0,0)[0]             : AIC=4328.253, Time=0.09 sec
 ARIMA(5,1,0)(0,0,0)[0]             : AIC=4331.507, Time=0.07 sec
 ARIMA(5,1,2)(0,0,0)[0]             : AIC=4330.604, Time=0.19 sec

Best model:  ARIMA(4,1,1)(0,0,0)[0]
Total fit time: 3.112 seconds

In [12]: model.predict(5)
Out[12]:
array([1161157.61296245, 1303987.30108932, 1275102.77902583,
       1102368.97324705, 1124238.73337648])
```

The only thing different in my code is that I omitted a few args that are defaults just to make it more readable. What version of the package are you running? Can you run the following?

```python
In [15]: pm.show_versions()

System:
    python: 3.6.7 |Anaconda, Inc.| (default, Oct 23 2018, 14:01:38)  [GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]
executable: /anaconda3/envs/pmdenv/bin/python
   machine: Darwin-18.7.0-x86_64-i386-64bit

Python dependencies:
        pip: 10.0.1
 setuptools: 40.5.0
    sklearn: 0.22.1
statsmodels: 0.11.1
      numpy: 1.19.0
      scipy: 1.4.1
     Cython: 0.29
     pandas: 0.24.2
     joblib: 0.13.2
   pmdarima: 0.0.0
```

**Comment by david686** [comment]
Hi,

**Comment by david686** [comment]
Hi,
i couldn't run the pm.show_versions()(it seems that my current version has no attribut show_version) but i have a requirement txt file on which:
statsmodels==0.9.0
pmdarima==1.2.0
scikit-learn==0.20.2
pandas==0.23.4
Cython==0.29.7
numpy==1.16.3
scipy==1.2.0
joblib==0.13.1

Thanks

**Comment by tgsmith61591** [comment]
You have a very old version. We are currently on 1.7.1. Please run `pip install --upgrade pmdarima`

**Comment by david686** [comment]
hi Taylor,

**Comment by david686** [comment]
Hi Taylor,
THANK you it was all about the version now it's work.
i run the pip upgrade on my laptop and there was a prediction, and to be sure, i did run on another laptop with the old version and the prediction was NaN.

**Comment by david686** [comment]
despite that it work with the new version of pmdarima, maybe tou have an idea of why the previous version didn't work.
could it be that some mathematical function combine with the data itself that did not work?
because i use quite a lot arima and it's the first time that i see this.
In my check i try to run it with the reverse data(data[::1]) and it work. 
it could be good to understand why this happen.

**Comment by tgsmith61591** [comment]
When I saw this in the past I believe it was related to the statsmodels version. You were nearly 3 minor versions behind on statsmodels, and 5 minor versions behind on pmdarima. We do not have a definitive reason as to why this occurred in older versions

**Comment by vcal-dedalus** [comment]
I'm facing the same problem with the following ENVIROMENT:
python: 3.9
pmdarima==2.0.3
statsmodels==0.14.0

The CODE to reproduce the error is:
`
training_data=np.array([[ 0.68701031],
       [-0.17725003],
       [-0.05378427],
       [-1.24728664],
       [-0.3830263 ],
       [-2.09096936],
       [-0.13609478],
       [ 0.02852624],
       [-0.23898291],
       [-0.11551715],
       [-0.3830263 ],
       [-0.46533681],
       [-0.13609478],
       [ 0.64585505]])
       
autofitted_model:pm.arima.ARIMA = pm.auto_arima(y=training_data, X=None, start_p=0, start_q=0,
                      test='adf',       
                      max_p=7, max_q=7, # maximum p and q
                      m=1,              # frequency of series
                      d=None,           # let model determine 'd'
                      seasonal=True,   # No Seasonality
                      start_P=0, 
                      D=0, 
                      trace=True,
                      error_action='ignore',  
                      suppress_warnings=True, 
                      stepwise=True)

prediction = autofitted_model.predict(n_periods=1, return_conf_int=False, X=None)
`
THE BUG:
After debugging inside pmdarima I found out that at a certain point 'statsmodels.tsa.statespace.kalman_smoother.SmootherResults' predicts 
-11.41263445 with a very small (but) **negative variance** -2.16770526e-09, which causes 'stasmodels.tsa.statespace.mlemodel.PredictionResults.**se_mean' property to be np.na** and, likewise the **confidence intervals** (returned by the function conf_int())

To sum up, because of certain work out in statsmodels, **pmdarima.arima.arima.py - line 167** gets a confidence interval such as [np.na, np.na] and afterwards, **in line 205, it calls check_array(.., force_all_finite=True)** (True by default). All this sequence of events, **even if you call predict(... return_conf_int=False...)**

SUGGESTED SOLUTION:
Even though I would like to know the confidence interval, I guess it should be statatsmodels who changes the code to return a numerical values instead of np.na. That said, what I would expected from ARIMA class is that confidence interval is not checked if I don't ask for it. I guess that would be easily solved just **adding a parameter to _seasonal_prediction_with_confidence (i.e. return_conf_int) that simply reflects choice made in ARIMA's predict(... return_conf_int=False..)**

**Comment by ChillTakeItEasy** [comment]
@vcal-dedalus Hi,
Did you manage to overcome this issue or still no updates on this?

Thanks

**Comment by vcal-dedalus** [comment]
No, sorry. No updates on this. I ended up applying other predictions models.
