### ISSUE TITLE
ImportError: cannot import name 'check_endog' from 'pmdarima.utils.array'

### ISSUE THREAD

**Issue by matiasrisso** [alkaline-ml/pmdarima#399]
When trying to import pmdarima 'import pmdarima as pm' I get this error. I have installed it using 'pip install pmdarima' and it's version 1.7.1

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-58-05191c3ae93f> in <module>
----> 1 import pmdarima as pm

~\anaconda3\lib\site-packages\pmdarima\__init__.py in <module>
     49 
     50     # Stuff we want at top-level
---> 51     from .arima import auto_arima, ARIMA, AutoARIMA, StepwiseContext, decompose
     52     from .utils import acf, autocorr_plot, c, pacf, plot_acf, plot_pacf, \
     53         tsdisplay

~\anaconda3\lib\site-packages\pmdarima\arima\__init__.py in <module>
      5 from .approx import *
      6 from .arima import *
----> 7 from .auto import *
      8 from .utils import *
      9 from .warnings import *

~\anaconda3\lib\site-packages\pmdarima\arima\auto.py in <module>
     18 from . import _doc
     19 from . import _validation as val
---> 20 from .utils import ndiffs, is_constant, nsdiffs
     21 from ..utils import diff, is_iterable, check_endog
     22 from ..utils.metaestimators import if_has_delegate

~\anaconda3\lib\site-packages\pmdarima\arima\utils.py in <module>
     12 from .. import context_managers as ctx
     13 from ..utils import get_callable
---> 14 from ..utils.array import diff, check_endog
     15 from ..compat.numpy import DTYPE
     16 from . import stationarity as statest_lib

ImportError: cannot import name 'check_endog' from 'pmdarima.utils.array' (C:\Users\matia\anaconda3\lib\site-packages\pmdarima\utils\array.py)

**Comment by tgsmith61591** [comment]
Can you run `pip freeze`?

**Comment by tgsmith61591** [comment]
Also what platform are you on?

**Comment by matiasrisso** [comment]
Now it seems to work just fine.
