### ISSUE TITLE
pmdarima setuptools update 

### ISSUE THREAD

**Issue by rodrigo-carvalho93** [alkaline-ml/pmdarima#401]
pmdarima 1.7.1 requires setuptools<50.0.0, but you'll have setuptools 50.3.2 which is incompatible.

I'm part of a team that's developing an app and we would like to use pmdarima to support our predictions, but we are having a big conflict with the version of setuptools. I heard it is pinned at version 50.0.0 because of some conflicts with distutils, but I wonder if you guys intend upgrading its version? 
I kinda tried to run-around this trouble making my own home-made auto_arima, but its defenitely not as good as the one you guys made. 
Thanks anyway! Keep up the awesome job

**Comment by aaronreidsmith** [comment]
Yeah, that's our bad. We had an issue in the middle of a release when they simultaneously released setuptools 50.0.0 (see #379 and https://github.com/pypa/setuptools/issues/2356), so we pinned it and I guess we forgot about it. I just opened #402  which should fix it, and we will get that out when we release 1.8.0 soon

**Comment by tgsmith61591** [comment]
Merged in #402. We will get 1.8.0 out this week with the fix included.
