### ISSUE TITLE
How to interpret the following model?

### ISSUE THREAD

**Issue by diogoalvesderesende** [alkaline-ml/pmdarima#415]
Hey,

This is a fantastic library, thank you for this. The output of the auto.arima gets me the following:

`Model: | SARIMAX(2, 0, 1)x(1, 0, [1, 2], 7)`

How do I interpret the [1,2]`?

Thanks in advance,
Diogo

**Comment by tgsmith61591** [comment]
From the statsmodels [SARIMAX documentation](https://www.statsmodels.org/dev/generated/statsmodels.tsa.statespace.sarimax.SARIMAX.html):

> The (P,D,Q,s) order of the seasonal component of the model for the AR parameters, differences, MA parameters, and periodicity. D must be an integer indicating the integration order of the process, while P and Q may either be an integers indicating the AR and MA orders (so that all lags up to those orders are included) or else iterables giving specific AR and / or MA lags to include.

Sorry for missing this one for so long.
