### ISSUE TITLE
OCSBTest

### ISSUE THREAD

**Issue by max-chernyshov** [alkaline-ml/pmdarima#418]
Hello colleagues! I have a question about the OCSBTest. I have data for 24 months and I would like to estimate the seasonality, but an error occurs .I will be grateful for your help!

Example:
```
data=np.array((1,2,3,4,5,6,7,8,9,10,12,1,2,3,4,5,6,7,8,9,10,12))
test=pm.arima.OCSBTest(12, lag_method='aic', max_lag=3)
test.estimate_seasonal_differencing_term(data)
```

ValueError: All lag values up to 'maxlag' produced singular matrices. Consider using a longer series, a different lag term or a different test.

**Comment by tgsmith61591** [comment]
Hey @max-chernyshov unfortunately the issue here is there is probably not enough data for the OCSB test to estimate the seasonal differencing term. I would encourage trying the CH test:

```python
import pmdarima as pm
import numpy as np

data = np.array((1,2,3,4,5,6,7,8,9,10,12,1,2,3,4,5,6,7,8,9,10,12))
test = pm.arima.CHTest(12)

>>> test.estimate_seasonal_differencing_term(data)
0
```
