### ISSUE TITLE
Cannot use with latest Cython 0.29.22

### ISSUE THREAD

**Issue by riderx** [alkaline-ml/pmdarima#420]
**Describe the bug**

**To Reproduce**  

```python
<YOUR CODE HERE>
```

**Versions**

**Expected behavior**

**Actual behavior**

**Additional context**

**Comment by aaronreidsmith** [comment]
Can you please fill in the issue template? We have nightly builds, and `pmdarima` successfully built last night with Cython 0.29.22 on Mac, Windows (32- and 64-bit), and Linux (Ubuntu).

https://github.com/alkaline-ml/pmdarima/runs/2243812323?check_suite_focus=true#step:10:17

**Comment by aaronreidsmith** [comment]
Closing due to lack of information. Feel free to re-open and fill in the provided issue template
