### ISSUE TITLE
Installed pmdarima but not found 😪

### ISSUE THREAD

**Issue by mertbozkir** [alkaline-ml/pmdarima#426]
**Question**
I tried several times to install pmdarima

**But, Why it is said pmdarima is not found?**

I installed pmdarima by pip
![image](https://user-images.githubusercontent.com/63906053/116382475-9eb3c980-a81e-11eb-8722-019b6ac8d061.png)

**When I try to import, this error shows itself.** 

![image](https://user-images.githubusercontent.com/63906053/116382007-2220eb00-a81e-11eb-9315-70fd07e4921d.png)

Edit: Python version: 3.8

**Comment by aaronreidsmith** [comment]
Since you are using Jupyter, it may be the case that Jupyter is pointing to a different version of Python than your shell is. Can you try this from _within_ a Jupyter notebook?

```
%pip install pmdarima
```

**Comment by mertbozkir** [comment]
Hmm, It worked. I understood why it's happening. Well said Aaron 👌

 Thank you 🐱‍👤
