### ISSUE TITLE
Unable to install pmdarima via Conda

### ISSUE THREAD

**Issue by ParthivNaresh** [alkaline-ml/pmdarima#429]
Describe the bug
As `pmdarima` is a soft dependency for `sktime`'s AutoARIMA, I am currently trying to install `pmdarima` via the conda route alongside `sktime`. Unfortunately, I'm unable to install `pmdarima` AND `sktime` via conda channels for a feedstock as it results in package conflicts.

To Reproduce
`conda install pmdarima`
`conda install sktime`

Essentially trying to install both `pmdarima` and `sktime` via conda results in conflicts. From what I understand, `pmdarima` [requires](https://github.com/conda-forge/pmdarima-feedstock/blob/master/recipe/meta.yaml) `statsmodels` to be `>=0.11,<0.12`, while `sktime` requires `statsmodels` to be `>=0.12.1`. I haven't been able to find any combination of requirements so far that can fix it. Even installing `sktime` and `pmdarima` (in either order) without pinning versions results in this error. As far as I can see, there's no way to install them both via conda due to conflicting dependencies.

Expected behavior
There shouldn't be any conflicts or the appropriate packages should be installed/upgraded/downgraded.

Versions
numpy >= 1.19.1
pandas >= 1.1.0
scikit-learn >= 0.23.1

System:
python: 3.8.0 | packaged by conda-forge | (default, Nov 22 2019, 19:11:19)  [Clang 9.0.0 (tags/RELEASE_900/final)]
executable: /Users/parthiv.naresh/miniconda3/envs/main/bin/python
   machine: macOS-10.15.7-x86_64-i386-64bit

Python dependencies:
pip: 21.1.1
setuptools: 49.6.0.post20210108
sklearn: 0.24.2
statsmodels: 0.12.2
numpy: 1.20.2
scipy: 1.6.3
Cython: 0.29.17
pandas: 1.2.4
joblib: 1.0.1
pmdarima: 1.8.0

**Comment by aaronreidsmith** [comment]
@ParthivNaresh can you try with the latest build that was [just pushed to conda-forge](https://anaconda.org/conda-forge/pmdarima/files)?

**Comment by mloning** [comment]
`conda create -n testenv python=3.8 sktime pmdarima -y` works for me without any conflicts - thanks for working on this @aaronreidsmith @ParthivNaresh!

**Comment by aaronreidsmith** [comment]
Awesome, thanks for the confirmation @mloning! I will go ahead and close this; feel free to re-open if the issue persists.
