### ISSUE TITLE
anaconda

### ISSUE THREAD

**Issue by pouriaI5O** [alkaline-ml/pmdarima#443]
how install latest version in anaconda?

**Comment by aaronreidsmith** [comment]
**Tl;dr**

```
conda config --add channels conda-forge
conda config --set channel_priority strict
conda install pmdarima
```

**Longer version**

We do not maintain the conda distribution ourselves, it is over at https://github.com/conda-forge/pmdarima-feedstock. Although, it may be worth adding something to our README to include this information and the link. The latest version currently available (on PyPI and Conda) is 1.8.2, with 1.8.3 coming soon.

See https://github.com/conda-forge/pmdarima-feedstock#installing-pmdarima for more detail.
