### ISSUE TITLE
Allow numpy versions greater than 1.19

### ISSUE THREAD

**Issue by freddyaboulton** [alkaline-ml/pmdarima#449]
**Is your feature request related to a problem? Please describe.**
pmdarima has a pin on numpy 1.19 version which forces uses to use 1.19 across their entire library/application even if they have other dependencies.

This is problematic because if a user's dependency has a pin on numpy>=1.20, then their package is broken.

We saw this in sktime, where numba introduced a lower bound on numpy>=1.20 https://github.com/numba/numba/issues/7339 and we couldn't upgrade numpy because then pmdarima could not be install ed.

Thank you!

**Describe the solution you'd like**
pmdarima depends on numpy>=1.19 or at least allow both numpy 1.19, 1.20

**Describe alternatives you've considered**

**Additional context**

**Comment by kasuteru** [comment]
I am having the same issue. I cannot downgrade my numpy version due to other packages requiring newer functionality.

**Comment by aaronreidsmith** [comment]
I'll look into this. We broke sktime when we tried to do this before (see #423, #425, and https://github.com/alan-turing-institute/sktime/pull/828, and https://github.com/alan-turing-institute/sktime/pull/831 for more detail) and they are much bigger than us, so we pinned it to what it is now. Hopefully I can whip something up!

**Comment by freddyaboulton** [comment]
@aaronreidsmith Thanks for looking into this! I see that #451 is passing all checks but hasn't been merged yet. Do you have an estimate of when it will be merged?

**Comment by freddyaboulton** [comment]
Thank you @aaronreidsmith and @tgsmith61591 !

**Comment by aaronreidsmith** [comment]
This should be fixed in version 1.8.3 which went out today

**Comment by freddyaboulton** [comment]
Thank you!
