### ISSUE TITLE
Coefficients of exogenous variables

### ISSUE THREAD

**Issue by preetha87** [alkaline-ml/pmdarima#45]
Hi,

My auto-ARIMA model includes exogenous variables.

When I try to print the model summary, the coefficient values, p values, z scores, etc. are not displaying for the exogenous variables included in the model.

How do I fix this?

Thanks,

Preetha

**Comment by preetha87** [comment]
Hi,

Thanks for replying.

Please find attached a zip folder containing the following:

a) The ipython notebook that contains the codes that I am running to build auto-ARIMA models and the output - I am building several ARIMA models simultaneously through a for loop as I am doing a demand planning exercise for a 1000 Stock Keeping Units at a Grocery store

b) The .csv files that I am importing for this exercise - there are 3 files - I am only able to upload only 2 csv files here as the 3rd one is huge (please advise as to where I can upload this third file - this file contains data on the dependent variable and several of the exogenous variables used in the model). 

c) A screen shot of the output produced by Auto-ARIMA for 1 SKU where the coefficients for the exogenous variables are not displaying.

I am using python 3.5, Anaconda distribution and a Jupyter notebook

[Auto_ARIMA_Example.zip](https://github.com/tgsmith61591/pyramid/files/2569128/Auto_ARIMA_Example.zip)

[Auto_ARIMA_Example - 2.zip](https://github.com/tgsmith61591/pyramid/files/2569135/Auto_ARIMA_Example.-.2.zip)


Hope this helps,

Preetha

**Comment by tgsmith61591** [comment]
Hey Preetha, thanks for taking the time to put this together. This is really a lot to include, and it's often easier for maintainers and other users who stumble upon similar issues if you include the examples inline (especially because you did not include the data required to run your Initial Results notebook - `paradise.csv`).  So, here's a pared-down version of what I understand your issue to be (using toy data and a random exogenous array):

```python
import numpy as np
from pyramid.arima import auto_arima
from pyramid.datasets import load_wineind

wineind = load_wineind()
exog = np.random.RandomState(1).rand(wineind.shape[0], 4)

arima = auto_arima(wineind, exogenous=exog, suppress_warnings=True,
                   stepwise=True, m=12, seasonal=True)
```

And your summary:

```python
>>> arima.summary()
<class 'statsmodels.iolib.summary.Summary'>
"""
                                 Statespace Model Results                                 
==========================================================================================
Dep. Variable:                                  y   No. Observations:                  176
Model:             SARIMAX(3, 1, 2)x(2, 0, 0, 12)   Log Likelihood               -1675.732
Date:                            Sun, 11 Nov 2018   AIC                           3377.465
Time:                                    13:43:48   BIC                           3418.607
Sample:                                         0   HQIC                          3394.153
                                            - 176                                         
Covariance Type:                              opg                                         
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
intercept   -458.2621    248.402     -1.845      0.065    -945.122      28.598
x1           904.7732   1013.367      0.893      0.372   -1081.389    2890.935
x2          -459.3297    909.302     -0.505      0.613   -2241.529    1322.870
x3         -2539.9125    862.585     -2.945      0.003   -4230.549    -849.277
x4         -1650.1780   1033.078     -1.597      0.110   -3674.973     374.617
ar.L1         -1.1259      0.080    -14.096      0.000      -1.282      -0.969
ar.L2         -0.3761      0.115     -3.265      0.001      -0.602      -0.150
ar.L3         -0.2501      0.074     -3.376      0.001      -0.395      -0.105
ma.L1          0.3212      0.051      6.324      0.000       0.222       0.421
ma.L2         -0.6788      0.054    -12.601      0.000      -0.784      -0.573
ar.S.L12       0.4952      0.061      8.131      0.000       0.376       0.615
ar.S.L24       0.3119      0.080      3.897      0.000       0.155       0.469
sigma2      1.233e+07      0.263   4.68e+07      0.000    1.23e+07    1.23e+07
===================================================================================
Ljung-Box (Q):                       18.70   Jarque-Bera (JB):                78.32
Prob(Q):                              1.00   Prob(JB):                         0.00
Heteroskedasticity (H):               0.60   Skew:                             0.06
Prob(H) (two-sided):                  0.05   Kurtosis:                         6.28
===================================================================================

Warnings:
[1] Covariance matrix calculated using the outer product of gradients (complex-step).
[2] Covariance matrix is singular or near-singular, with condition number 6.37e+22. Standard errors may be unstable.
"""
```

And I'm seeing coefficients for the exogenous array (`x1`, `x1`, etc...). So I cannot reproduce the error you're running into... but perhaps it has to do with your statsmodels version? SM is the library that produces the summary report, so it's not something I could fix anyways. The version I have is 0.9.0. See if you can reproduce my results running the example included above.

**Comment by Anaisdg** [comment]
Hello @tgsmith61591, 
I have the same issue as OP.  I'm using the msft dataset instead. Can you please help me? 
```
import pmdarima as pm
from pmdarima.arima import auto_arima
from pmdarima import model_selection
from pmdarima.pipeline import Pipeline
from pmdarima.datasets import load_msft
```
```
msft = load_msft()
data = msft.values
train, test = model_selection.train_test_split(data, train_size=800)
exo_model = pm.auto_arima(train[:,1], trace=True, suppress_warnings=True,exogeneous=train[:,2:5], stationarity=False, seasonality=True)
```
<img width="967" alt="Screen Shot 2020-03-17 at 5 11 08 PM" src="https://user-images.githubusercontent.com/30506042/76906615-59c71080-6872-11ea-88e0-7ad870709ef3.png">

```
exo_model.summary()
```

<img width="624" alt="Screen Shot 2020-03-17 at 5 11 12 PM" src="https://user-images.githubusercontent.com/30506042/76906632-66e3ff80-6872-11ea-9cc2-39c54ad11571.png">

**Comment by tgsmith61591** [comment]
You misspelled "exogenous"

**Comment by shuyi-li** [comment]
@Anaisdg , I just experienced the same issue as you did. I later noticed that in the documents of pmdarima, the exogenous variables are fed to .fit() so I did that and it worked for me. Hope this helps you too.

**Comment by Shane-McCallum** [comment]
Hello, I am trying to predict with my auto_arima model. 
```
train_len = int(maindf.shape[0] * 0.8)
train_data, test_data = maindf[:train_len], maindf[train_len:]

y_train = train_data['GLD(USD)'].values
y_test = test_data['GLD(USD)'].values

print(f"{train_len} train samples")
print(f"{df.shape[0] - train_len} test samples")

from pmdarima.arima import ndiffs

kpss_diffs = ndiffs(y_train, alpha=0.05, test='kpss', max_d=6)
adf_diffs = ndiffs(y_train, alpha=0.05, test='adf', max_d=6)
n_diffs = max(adf_diffs, kpss_diffs)

print(f"Estimated differencing term: {n_diffs}")

auto = pm.auto_arima(y_train, x=train_data['SPX(USD)'], d=n_diffs, seasonal=False, stepwise=True, 
                     suppress_warnings=True, error_action="ignore", max_p=6, max_order=None, trace=True)
```
All of this works up until I try to predict:

```
def forecast_one_step():
    fc, conf_int = model.predict(n_periods=1, X=train_data['SPX(USD)'], return_conf_int=True)
    return (
        fc.tolist()[0],
        np.asarray(conf_int).tolist()[0])

forecasts = []
confidence_intervals = []

for new_ob in y_test:
    fc, conf = forecast_one_step()
    forecasts.append(fc)
    confidence_intervals.append(conf)

    # Updates the existing model with a small number of MLE steps
    model.update(new_ob)

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-209-6f62136c17e0> in <module>
      9 
     10 for new_ob in y_test:
---> 11     fc, conf = forecast_one_step()
     12     forecasts.append(fc)
     13     confidence_intervals.append(conf)

<ipython-input-209-6f62136c17e0> in forecast_one_step()
      1 def forecast_one_step():
----> 2     fc, conf_int = model.predict(n_periods=1, X=train_data['SPX(USD)'], return_conf_int=True)
      3     return (
      4         fc.tolist()[0],
      5         np.asarray(conf_int).tolist()[0])

~\anaconda3\lib\site-packages\pmdarima\arima\arima.py in predict(self, n_periods, X, return_conf_int, alpha, **kwargs)
    666 
    667         # if we fit with exog, make sure one was passed:
--> 668         X = self._check_exog(X)  # type: np.ndarray
    669         if X is not None and X.shape[0] != n_periods:
    670             raise ValueError('X array dims (n_rows) != n_periods')

~\anaconda3\lib\site-packages\pmdarima\arima\arima.py in _check_exog(self, X)
    510                                  'predicting or updating observations.')
    511             else:
--> 512                 return check_exog(X, force_all_finite=True, dtype=DTYPE)
    513         return None
    514 

~\anaconda3\lib\site-packages\pmdarima\utils\array.py in check_exog(X, dtype, copy, force_all_finite)
    202     """
    203     if hasattr(X, 'ndim') and X.ndim != 2:
--> 204         raise ValueError("Must be a 2-d array or dataframe")
    205 
    206     if isinstance(X, pd.DataFrame):

ValueError: Must be a 2-d array or dataframe
```

Any advice?

**Comment by trbella** [comment]
> You misspelled "exogenous"

Even if you use "exogenous", pmdarima (1.8.0) will not recognize the exogenous variable.
In the documentation they are called 'y' for endogenous and 'X' for exogenous.
The first time I tried to fit the model, calling exogenous = "my_exog", the summary did not show me the exogenous coefficients, but, when I just called it without writting the name of the argument, worked fine.

`import pmdarima as pm`

`sxmodel = pm.auto_arima(endog[:n_train],exog[:n_train], start_p=0, start_q=0, max_p=1, max_q=1,
                           test='adf',start_P=0,start_Q=0, max_P=1,max_D=1,max_Q=1, m=7, seasonal=True,
                           d=None, trace=True, error_action='trace',suppress_warnings=True, stepwise=True)`

`print(sxmodel.summary())`

![Capturar](https://user-images.githubusercontent.com/63654426/110995207-b3b0c800-8358-11eb-980d-d9c3be9a0b03.PNG)

**Comment by tgsmith61591** [comment]
> Even if you use "exogenous", pmdarima (1.8.0) will not recognize the exogenous variable.
In the documentation they are called 'y' for endogenous and 'X' for exogenous.

Just FYI even though we've renamed that to `X` we still continue to recognize `exogenous` until the next major release (2.0 -- see [the PR](https://github.com/alkaline-ml/pmdarima/pull/385) for more background). But yes, the issue here was the misspelling.
