### ISSUE TITLE
scikit-learn 1.0 breaks builds

### ISSUE THREAD

**Issue by aaronreidsmith** [alkaline-ml/pmdarima#454]
### Describe the bug

scikit learn 1.0 was [released this morning](https://pypi.org/project/scikit-learn/#history) and is [breaking our builds](https://github.com/alkaline-ml/pmdarima/actions/runs/1269997034). This issue is for tracking work around getting tests to pass with scikit-learn 1.0

### To Reproduce

`make bdist_wheel`

### Versions

See the `Install Requirements` step here: https://github.com/alkaline-ml/pmdarima/runs/3700467105?check_suite_focus=true

### Expected Behavior

`pmdarima` passes tests

### Actual Behavior

`pmdarima` does not pass tests

**Comment by Zahlii** [comment]
Can confirm that the exact same bug also happens in our testing pipeline build atop on pmdarima with the exact same reason.

**Comment by Zahlii** [comment]
TBH I think this is a bug in scikit-learn itself; here is a workaround I found

![image](https://user-images.githubusercontent.com/218582/134700237-f1a22f41-bb08-4dd9-9f2c-6c9de4d5783d.png)

**Comment by aaronreidsmith** [comment]
I think #455 should fix this without relying on a sklearn release

**Comment by microprediction** [comment]
Noticed this too. I'll try your patch.

**Comment by aaronreidsmith** [comment]
This should be fixed in version 1.8.3 which went out today
