### ISSUE TITLE
When will the next release of pmdarima be available?

### ISSUE THREAD

**Issue by jayc-stripe** [alkaline-ml/pmdarima#466]
### Describe the question you have

Hello! I'm currently working on a project that requires both statsmodel 0.13.0 and pmdarima. I noticed that pmdarima added support for statsmodel 0.13.0 in https://github.com/alkaline-ml/pmdarima/pull/457, but unfortunately I am required to use a tagged version of pmdarima and so cannot just pull in the bleeding edge version of pmdarima. We have other workarounds for the time being, but are curious -- when will the next release of pmdarima be available? Please let us know, thank you!

**Comment by aaronreidsmith** [comment]
Thanks for the question! I just opened #467 to update our docs for a 1.8.4 release. We will shoot to merge that and release tomorrow, 2021-11-05

**Comment by jayc-stripe** [comment]
Wow that's an amazing turnaround time. Thank you!

**Comment by aaronreidsmith** [comment]
1.8.4 was deployed this morning. Just a note, we only maintain the wheels in this repo. If you are a conda user, those releases are maintained [here](https://github.com/conda-forge/pmdarima-feedstock).

**Comment by jayc-stripe** [comment]
Thanks again!
