### ISSUE TITLE
remove matplotlib as a dependency

### ISSUE THREAD

**Issue by jeweinberg** [alkaline-ml/pmdarima#47]
Can we please remove the matplotlib dependency? I do not use it in my applications and I don't want this to be a dependency of the environment I am maintaining.

**Comment by tgsmith61591** [comment]
Matplotlib is required for the ACF and PACF plotting functions. I'm not sure why having matplotlib around poses a problem... You can always fork and remove functions/dependencies you don't need

**Comment by jeweinberg** [comment]
I wasn't meaning in removing the functionality from your package (which is fantastic btw). Just remove the install from the pip requirements. If people want to use the plotting functions you would just throw an error saying they need to install matplotlib separately. I think this is pretty common behavior for statistical packages in python that include some plotting functionality.

**Comment by tgsmith61591** [comment]
Gotcha. Here's what that would require (just off the top of my head):

* [ ] (Obviously) remove `matplotlib` from `requirements.txt`
* [ ] Handle situation in `pmdarima.utils.visualization` where we cannot import `matplotlib`. This is actually technically already handled [here](https://github.com/tgsmith61591/pmdarima/blob/master/pmdarima/utils/visualization.py#L42) with a warning raised [here](https://github.com/tgsmith61591/pmdarima/blob/master/pmdarima/utils/visualization.py#L52) for no matplotlib installed. But as the issue connotes, we never allow that to be the case given the requirements.
* [ ] We may want to get a bit more severe with how we handle a user trying to call a plotting function even if they've already been warned. Currently, we're just warning again (see [here](https://github.com/tgsmith61591/pmdarima/blob/master/pmdarima/utils/visualization.py#L100), for instance), but it might make more sense to raise an `ImportError` similar to [how Pandas does](https://stackoverflow.com/questions/52701688/pandas-importerror-matplotlib-is-required-for-plotting)
* [ ] (Most complex) handle specific test cases in CI suites for `matplotlib` missing and make assertions on the expected errors, warnings, etc. Also will have to more explicitly install the library on Travis, Appveyor and some of the Circle jobs (not the doc one, as it handles it already)

I won't be able to address this immediately, so if you (or anyone) would like to take a crack at it, be my guest.

**Comment by charlesdrotar** [comment]
@tgsmith61591 looked at the setup.py just to doubly verify that it wasn't pulling in the requirement from elsewhere and [it basically parses `requirements.txt`](https://github.com/tgsmith61591/pmdarima/blob/master/setup.py#L46-L48) and [uses the lines of the file to create the list for the `install_requires`](https://github.com/tgsmith61591/pmdarima/blob/master/setup.py#L108) so with that I am not sure how MPL would be getting pulled in either....maybe an older `.whl` possibly?

That aside the issue did generate some valuable talking points as to how best to gracefully handle this situation within the code. As to your point of raising an `ImportError`, [that is the behavior I have seen in statsmodels](https://github.com/statsmodels/statsmodels/blob/master/statsmodels/graphics/utils.py#L7-L14) as well when MPL is not available for its plot functions.

**Comment by tgsmith61591** [comment]
Thanks for weighing in @charlesdrotar. Yeah, I think we're handling all but the last two (namely, a specific set of functional tests for CI that do *not* include `matplotlib` and we should probably raise rather than warn).

@jeweinberg can you please answer where you were having issues? It doesn't appear `matplotlib` was ever in the `requirements.txt`?
