### ISSUE TITLE
predict parallel

### ISSUE THREAD

**Issue by junsyw** [alkaline-ml/pmdarima#471]
### Describe the question you have

Hello
I am very grateful for this library, it has helped me a lot but I have a question, it is possible to parallelize the prediction part
model.predict ()
Thanks

**Comment by tgsmith61591** [comment]
This is not possible and unlikely to be easy to add. Are you finding `predict` to be slow for your usecase?

**Comment by junsyw** [comment]
It doesn't take long, just that I have a model that is already paralleled in the part of optimizing the extra parameters, so I thought about earning a little more, parallelizing the prediction part of the best model

**Comment by tgsmith61591** [comment]
Gotcha. This wouldn't give you much performance lift and we don't have any control over the portion of the code that would need to change to allow this. So it's not going to be a possibility
