### ISSUE TITLE
Support python 3.10

### ISSUE THREAD

**Issue by freddyaboulton** [alkaline-ml/pmdarima#481]
### Is your feature request related to a problem? Please describe.

pmd arima does not publish wheels for python 3.10:

https://pypi.org/project/pmdarima/#files .

This means users have to build pmdarima from source if they want to use it in python 3.10. 

### Describe the solution you'd like

pmdarima publishes pre-built wheels for python 3.10 for windows, mac, linux. 

### Describe alternatives you've considered

-

**Comment by aaronreidsmith** [comment]
Yep, agreed. We added 3.10 support in `master` with #459 but we need to get a release out so people can actually use it. We'll get one out soon!

**Comment by bashtage** [comment]
You might want to check if you can bump the supported statsmodels to something more recent. >=0.11, <0.12 is pretty old these days and the only versions that support 3.10 (officially, and have wheels) are >=0.13. Aside from this there have been a number of improvements to the statespace code in this period, although some may break tests.

**Comment by tgsmith61591** [comment]
Version 1.8.5 was released this morning and includes builds for Python 3.10
