### ISSUE TITLE
cc1: error: pmdarima/arima/_arima_fast_helpers.h: not a directory

### ISSUE THREAD

**Issue by sinall** [alkaline-ml/pmdarima#482]
### Describe the bug

> Installing collected packages: pmdarima
>     Running setup.py install for pmdarima ... error
>     ERROR: Command errored out with exit status 1:
>      command: /usr/bin/python3.6 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-huof5vb0/pmdarima/setup.py'"'"'; __file__='"'"'/tmp/pip-install-huof5vb0/pmdarima/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-51fufzm6/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.6m/pmdarima
>          cwd: /tmp/pip-install-huof5vb0/pmdarima/
>     Complete output (245 lines):
>     Partial import of pmdarima during the build process.
>     Requirements: ['joblib>=0.11', 'Cython>=0.29,!=0.29.18', 'numpy>=1.19.3', 'pandas>=0.19', 'scikit-learn>=0.22', 'scipy>=1.3.2', 'statsmodels>=0.11,!=0.12.0', 'urllib3', 'setuptools>=38.6.0,!=50.0.0']
>     Adding extra setuptools args
>     Setting up with numpy.distutils.core
>     blas_opt_info:
>     blas_mkl_info:
>     customize UnixCCompiler
>       libraries mkl_rt not found in ['/usr/local/lib64', '/usr/local/lib', '/usr/lib64', '/usr/lib']
>       NOT AVAILABLE
> 
>     blis_info:
>       libraries blis not found in ['/usr/local/lib64', '/usr/local/lib', '/usr/lib64', '/usr/lib']
>       NOT AVAILABLE
> 
>     openblas_info:
>       libraries openblas not found in ['/usr/local/lib64', '/usr/local/lib', '/usr/lib64', '/usr/lib']
>       NOT AVAILABLE
> 
>     atlas_3_10_blas_threads_info:
>     Setting PTATLAS=ATLAS
>       libraries tatlas not found in ['/usr/local/lib64', '/usr/local/lib', '/usr/lib64/sse2', '/usr/lib64', '/usr/lib']
>       NOT AVAILABLE
> 
>     atlas_3_10_blas_info:
>       libraries satlas not found in ['/usr/local/lib64', '/usr/local/lib', '/usr/lib64/sse2', '/usr/lib64', '/usr/lib']
>       NOT AVAILABLE
> 
>     atlas_blas_threads_info:
>     Setting PTATLAS=ATLAS
>       libraries ptf77blas,ptcblas,atlas not found in ['/usr/local/lib64', '/usr/local/lib', '/usr/lib64/sse2', '/usr/lib64', '/usr/lib']
>       NOT AVAILABLE
> 
>     atlas_blas_info:
>       libraries f77blas,cblas,atlas not found in ['/usr/local/lib64', '/usr/local/lib', '/usr/lib64/sse2', '/usr/lib64', '/usr/lib']
>       NOT AVAILABLE
> 
>     accelerate_info:
>       NOT AVAILABLE
> 
>     /usr/local/lib64/python3.6/site-packages/numpy/distutils/system_info.py:1914: UserWarning:
>         Optimized (vendor) Blas libraries are not found.
>         Falls back to netlib Blas library which has worse performance.
>         A better performance should be easily gained by switching
>         Blas library.
>       if self._calc_info(blas):
>     blas_info:
>       libraries blas not found in ['/usr/local/lib64', '/usr/local/lib', '/usr/lib64', '/usr/lib']
>       NOT AVAILABLE
> 
>     /usr/local/lib64/python3.6/site-packages/numpy/distutils/system_info.py:1914: UserWarning:
>         Blas (http://www.netlib.org/blas/) libraries not found.
>         Directories to search for the libraries can be specified in the
>         numpy/distutils/site.cfg file (section [blas]) or by setting
>         the BLAS environment variable.
>       if self._calc_info(blas):
>     blas_src_info:
>       NOT AVAILABLE
> 
>     /usr/local/lib64/python3.6/site-packages/numpy/distutils/system_info.py:1914: UserWarning:
>         Blas (http://www.netlib.org/blas/) sources not found.
>         Directories to search for the sources can be specified in the
>         numpy/distutils/site.cfg file (section [blas_src]) or by setting
>         the BLAS_SRC environment variable.
>       if self._calc_info(blas):
>       NOT AVAILABLE
> 
>     C compiler: gcc -pthread -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC
> 
>     compile options: '-c'
>     gcc: test_program.c
>     gcc -pthread objects/test_program.o -o test_program
>     Compiling pmdarima/__check_build/_check_build.pyx because it changed.
>     Compiling pmdarima/arima/_arima.pyx because it changed.
>     Compiling pmdarima/preprocessing/exog/_fourier.pyx because it changed.
>     Compiling pmdarima/utils/_array.pyx because it changed.
>     [1/4] Cythonizing pmdarima/__check_build/_check_build.pyx
>     [2/4] Cythonizing pmdarima/arima/_arima.pyx
>     [3/4] Cythonizing pmdarima/preprocessing/exog/_fourier.pyx
>     [4/4] Cythonizing pmdarima/utils/_array.pyx
>     running install
>     running build
>     running config_cc
>     unifing config_cc, config, build_clib, build_ext, build commands --compiler options
>     running config_fc
>     unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
>     running build_src
>     build_src
>     building extension "pmdarima.__check_build._check_build" sources
>     building extension "pmdarima.arima._arima" sources
>     building extension "pmdarima.preprocessing.exog._fourier" sources
>     building extension "pmdarima.utils._array" sources
>     building data_files sources
>     build_src: building npy-pkg config files
>     running build_py
>     creating build
>     creating build/lib.linux-x86_64-3.6
>     creating build/lib.linux-x86_64-3.6/pmdarima
>     copying pmdarima/metrics.py -> build/lib.linux-x86_64-3.6/pmdarima
>     copying pmdarima/warnings.py -> build/lib.linux-x86_64-3.6/pmdarima
>     copying pmdarima/decorators.py -> build/lib.linux-x86_64-3.6/pmdarima
>     copying pmdarima/setup.py -> build/lib.linux-x86_64-3.6/pmdarima
>     copying pmdarima/__init__.py -> build/lib.linux-x86_64-3.6/pmdarima
>     copying pmdarima/pipeline.py -> build/lib.linux-x86_64-3.6/pmdarima
>     copying pmdarima/base.py -> build/lib.linux-x86_64-3.6/pmdarima
>     copying pmdarima/context_managers.py -> build/lib.linux-x86_64-3.6/pmdarima
>     creating build/lib.linux-x86_64-3.6/pmdarima/__check_build
>     copying pmdarima/__check_build/setup.py -> build/lib.linux-x86_64-3.6/pmdarima/__check_build
>     copying pmdarima/__check_build/__init__.py -> build/lib.linux-x86_64-3.6/pmdarima/__check_build
>     creating build/lib.linux-x86_64-3.6/pmdarima/_build_utils
>     copying pmdarima/_build_utils/pre_build_helpers.py -> build/lib.linux-x86_64-3.6/pmdarima/_build_utils
>     copying pmdarima/_build_utils/__init__.py -> build/lib.linux-x86_64-3.6/pmdarima/_build_utils
>     creating build/lib.linux-x86_64-3.6/pmdarima/compat
>     copying pmdarima/compat/pmdarima.py -> build/lib.linux-x86_64-3.6/pmdarima/compat
>     copying pmdarima/compat/sklearn.py -> build/lib.linux-x86_64-3.6/pmdarima/compat
>     copying pmdarima/compat/statsmodels.py -> build/lib.linux-x86_64-3.6/pmdarima/compat
>     copying pmdarima/compat/pytest.py -> build/lib.linux-x86_64-3.6/pmdarima/compat
>     copying pmdarima/compat/matplotlib.py -> build/lib.linux-x86_64-3.6/pmdarima/compat
>     copying pmdarima/compat/__init__.py -> build/lib.linux-x86_64-3.6/pmdarima/compat
>     copying pmdarima/compat/pandas.py -> build/lib.linux-x86_64-3.6/pmdarima/compat
>     copying pmdarima/compat/numpy.py -> build/lib.linux-x86_64-3.6/pmdarima/compat
>     creating build/lib.linux-x86_64-3.6/pmdarima/compat/tests
>     copying pmdarima/compat/tests/test_statsmodels.py -> build/lib.linux-x86_64-3.6/pmdarima/compat/tests
>     copying pmdarima/compat/tests/test_sklearn.py -> build/lib.linux-x86_64-3.6/pmdarima/compat/tests
>     copying pmdarima/compat/tests/__init__.py -> build/lib.linux-x86_64-3.6/pmdarima/compat/tests
>     copying pmdarima/compat/tests/test_pmdarima.py -> build/lib.linux-x86_64-3.6/pmdarima/compat/tests
>     creating build/lib.linux-x86_64-3.6/pmdarima/datasets
>     copying pmdarima/datasets/lynx.py -> build/lib.linux-x86_64-3.6/pmdarima/datasets
>     copying pmdarima/datasets/austres.py -> build/lib.linux-x86_64-3.6/pmdarima/datasets
>     copying pmdarima/datasets/heartrate.py -> build/lib.linux-x86_64-3.6/pmdarima/datasets
>     copying pmdarima/datasets/taylor.py -> build/lib.linux-x86_64-3.6/pmdarima/datasets
>     copying pmdarima/datasets/ausbeer.py -> build/lib.linux-x86_64-3.6/pmdarima/datasets
>     copying pmdarima/datasets/gasoline.py -> build/lib.linux-x86_64-3.6/pmdarima/datasets
>     copying pmdarima/datasets/wineind.py -> build/lib.linux-x86_64-3.6/pmdarima/datasets
>     copying pmdarima/datasets/setup.py -> build/lib.linux-x86_64-3.6/pmdarima/datasets
>     copying pmdarima/datasets/__init__.py -> build/lib.linux-x86_64-3.6/pmdarima/datasets
>     copying pmdarima/datasets/sunspots.py -> build/lib.linux-x86_64-3.6/pmdarima/datasets
>     copying pmdarima/datasets/woolyrnq.py -> build/lib.linux-x86_64-3.6/pmdarima/datasets
>     copying pmdarima/datasets/stocks.py -> build/lib.linux-x86_64-3.6/pmdarima/datasets
>     copying pmdarima/datasets/_base.py -> build/lib.linux-x86_64-3.6/pmdarima/datasets
>     copying pmdarima/datasets/airpassengers.py -> build/lib.linux-x86_64-3.6/pmdarima/datasets
>     creating build/lib.linux-x86_64-3.6/pmdarima/datasets/tests
>     copying pmdarima/datasets/tests/__init__.py -> build/lib.linux-x86_64-3.6/pmdarima/datasets/tests
>     copying pmdarima/datasets/tests/test_load_datasets.py -> build/lib.linux-x86_64-3.6/pmdarima/datasets/tests
>     creating build/lib.linux-x86_64-3.6/pmdarima/model_selection
>     copying pmdarima/model_selection/_split.py -> build/lib.linux-x86_64-3.6/pmdarima/model_selection
>     copying pmdarima/model_selection/_validation.py -> build/lib.linux-x86_64-3.6/pmdarima/model_selection
>     copying pmdarima/model_selection/__init__.py -> build/lib.linux-x86_64-3.6/pmdarima/model_selection
>     creating build/lib.linux-x86_64-3.6/pmdarima/model_selection/tests
>     copying pmdarima/model_selection/tests/test_validation.py -> build/lib.linux-x86_64-3.6/pmdarima/model_selection/tests
>     copying pmdarima/model_selection/tests/__init__.py -> build/lib.linux-x86_64-3.6/pmdarima/model_selection/tests
>     copying pmdarima/model_selection/tests/test_split.py -> build/lib.linux-x86_64-3.6/pmdarima/model_selection/tests
>     creating build/lib.linux-x86_64-3.6/pmdarima/arima
>     copying pmdarima/arima/_context.py -> build/lib.linux-x86_64-3.6/pmdarima/arima
>     copying pmdarima/arima/_auto_solvers.py -> build/lib.linux-x86_64-3.6/pmdarima/arima
>     copying pmdarima/arima/auto.py -> build/lib.linux-x86_64-3.6/pmdarima/arima
>     copying pmdarima/arima/approx.py -> build/lib.linux-x86_64-3.6/pmdarima/arima
>     copying pmdarima/arima/stationarity.py -> build/lib.linux-x86_64-3.6/pmdarima/arima
>     copying pmdarima/arima/setup.py -> build/lib.linux-x86_64-3.6/pmdarima/arima
>     copying pmdarima/arima/_validation.py -> build/lib.linux-x86_64-3.6/pmdarima/arima
>     copying pmdarima/arima/utils.py -> build/lib.linux-x86_64-3.6/pmdarima/arima
>     copying pmdarima/arima/__init__.py -> build/lib.linux-x86_64-3.6/pmdarima/arima
>     copying pmdarima/arima/_doc.py -> build/lib.linux-x86_64-3.6/pmdarima/arima
>     copying pmdarima/arima/seasonality.py -> build/lib.linux-x86_64-3.6/pmdarima/arima
>     copying pmdarima/arima/arima.py -> build/lib.linux-x86_64-3.6/pmdarima/arima
>     creating build/lib.linux-x86_64-3.6/pmdarima/arima/tests
>     copying pmdarima/arima/tests/test_auto_solvers.py -> build/lib.linux-x86_64-3.6/pmdarima/arima/tests
>     copying pmdarima/arima/tests/test_c_arima.py -> build/lib.linux-x86_64-3.6/pmdarima/arima/tests
>     copying pmdarima/arima/tests/test_auto.py -> build/lib.linux-x86_64-3.6/pmdarima/arima/tests
>     copying pmdarima/arima/tests/test_stationarity.py -> build/lib.linux-x86_64-3.6/pmdarima/arima/tests
>     copying pmdarima/arima/tests/test_validation.py -> build/lib.linux-x86_64-3.6/pmdarima/arima/tests
>     copying pmdarima/arima/tests/test_seasonality.py -> build/lib.linux-x86_64-3.6/pmdarima/arima/tests
>     copying pmdarima/arima/tests/test_arima_diagnostics.py -> build/lib.linux-x86_64-3.6/pmdarima/arima/tests
>     copying pmdarima/arima/tests/__init__.py -> build/lib.linux-x86_64-3.6/pmdarima/arima/tests
>     copying pmdarima/arima/tests/test_approx.py -> build/lib.linux-x86_64-3.6/pmdarima/arima/tests
>     copying pmdarima/arima/tests/test_arima.py -> build/lib.linux-x86_64-3.6/pmdarima/arima/tests
>     copying pmdarima/arima/tests/test_context.py -> build/lib.linux-x86_64-3.6/pmdarima/arima/tests
>     copying pmdarima/arima/tests/test_utils.py -> build/lib.linux-x86_64-3.6/pmdarima/arima/tests
>     creating build/lib.linux-x86_64-3.6/pmdarima/preprocessing
>     copying pmdarima/preprocessing/setup.py -> build/lib.linux-x86_64-3.6/pmdarima/preprocessing
>     copying pmdarima/preprocessing/__init__.py -> build/lib.linux-x86_64-3.6/pmdarima/preprocessing
>     copying pmdarima/preprocessing/base.py -> build/lib.linux-x86_64-3.6/pmdarima/preprocessing
>     creating build/lib.linux-x86_64-3.6/pmdarima/preprocessing/endog
>     copying pmdarima/preprocessing/endog/__init__.py -> build/lib.linux-x86_64-3.6/pmdarima/preprocessing/endog
>     copying pmdarima/preprocessing/endog/log.py -> build/lib.linux-x86_64-3.6/pmdarima/preprocessing/endog
>     copying pmdarima/preprocessing/endog/base.py -> build/lib.linux-x86_64-3.6/pmdarima/preprocessing/endog
>     copying pmdarima/preprocessing/endog/boxcox.py -> build/lib.linux-x86_64-3.6/pmdarima/preprocessing/endog
>     creating build/lib.linux-x86_64-3.6/pmdarima/preprocessing/endog/tests
>     copying pmdarima/preprocessing/endog/tests/test_boxcox.py -> build/lib.linux-x86_64-3.6/pmdarima/preprocessing/endog/tests
>     copying pmdarima/preprocessing/endog/tests/test_log.py -> build/lib.linux-x86_64-3.6/pmdarima/preprocessing/endog/tests
>     copying pmdarima/preprocessing/endog/tests/__init__.py -> build/lib.linux-x86_64-3.6/pmdarima/preprocessing/endog/tests
>     copying pmdarima/preprocessing/endog/tests/test_base.py -> build/lib.linux-x86_64-3.6/pmdarima/preprocessing/endog/tests
>     creating build/lib.linux-x86_64-3.6/pmdarima/preprocessing/exog
>     copying pmdarima/preprocessing/exog/dates.py -> build/lib.linux-x86_64-3.6/pmdarima/preprocessing/exog
>     copying pmdarima/preprocessing/exog/setup.py -> build/lib.linux-x86_64-3.6/pmdarima/preprocessing/exog
>     copying pmdarima/preprocessing/exog/__init__.py -> build/lib.linux-x86_64-3.6/pmdarima/preprocessing/exog
>     copying pmdarima/preprocessing/exog/fourier.py -> build/lib.linux-x86_64-3.6/pmdarima/preprocessing/exog
>     copying pmdarima/preprocessing/exog/base.py -> build/lib.linux-x86_64-3.6/pmdarima/preprocessing/exog
>     creating build/lib.linux-x86_64-3.6/pmdarima/preprocessing/exog/tests
>     copying pmdarima/preprocessing/exog/tests/test_dates.py -> build/lib.linux-x86_64-3.6/pmdarima/preprocessing/exog/tests
>     copying pmdarima/preprocessing/exog/tests/__init__.py -> build/lib.linux-x86_64-3.6/pmdarima/preprocessing/exog/tests
>     copying pmdarima/preprocessing/exog/tests/test_base.py -> build/lib.linux-x86_64-3.6/pmdarima/preprocessing/exog/tests
>     copying pmdarima/preprocessing/exog/tests/test_fourier.py -> build/lib.linux-x86_64-3.6/pmdarima/preprocessing/exog/tests
>     creating build/lib.linux-x86_64-3.6/pmdarima/utils
>     copying pmdarima/utils/visualization.py -> build/lib.linux-x86_64-3.6/pmdarima/utils
>     copying pmdarima/utils/metaestimators.py -> build/lib.linux-x86_64-3.6/pmdarima/utils
>     copying pmdarima/utils/_show_versions.py -> build/lib.linux-x86_64-3.6/pmdarima/utils
>     copying pmdarima/utils/setup.py -> build/lib.linux-x86_64-3.6/pmdarima/utils
>     copying pmdarima/utils/array.py -> build/lib.linux-x86_64-3.6/pmdarima/utils
>     copying pmdarima/utils/__init__.py -> build/lib.linux-x86_64-3.6/pmdarima/utils
>     copying pmdarima/utils/wrapped.py -> build/lib.linux-x86_64-3.6/pmdarima/utils
>     creating build/lib.linux-x86_64-3.6/pmdarima/utils/tests
>     copying pmdarima/utils/tests/test_wrapped.py -> build/lib.linux-x86_64-3.6/pmdarima/utils/tests
>     copying pmdarima/utils/tests/__init__.py -> build/lib.linux-x86_64-3.6/pmdarima/utils/tests
>     copying pmdarima/utils/tests/test_vis.py -> build/lib.linux-x86_64-3.6/pmdarima/utils/tests
>     copying pmdarima/utils/tests/test_show_versions.py -> build/lib.linux-x86_64-3.6/pmdarima/utils/tests
>     copying pmdarima/utils/tests/test_array.py -> build/lib.linux-x86_64-3.6/pmdarima/utils/tests
>     copying pmdarima/utils/tests/test_meta.py -> build/lib.linux-x86_64-3.6/pmdarima/utils/tests
>     creating build/lib.linux-x86_64-3.6/pmdarima/tests
>     copying pmdarima/tests/test_pipeline.py -> build/lib.linux-x86_64-3.6/pmdarima/tests
>     copying pmdarima/tests/test_metrics.py -> build/lib.linux-x86_64-3.6/pmdarima/tests
>     copying pmdarima/tests/test_estimators.py -> build/lib.linux-x86_64-3.6/pmdarima/tests
>     copying pmdarima/tests/test_benchmarks.py -> build/lib.linux-x86_64-3.6/pmdarima/tests
>     copying pmdarima/tests/__init__.py -> build/lib.linux-x86_64-3.6/pmdarima/tests
>     copying pmdarima/tests/test_context_managers.py -> build/lib.linux-x86_64-3.6/pmdarima/tests
>     running build_ext
>     customize UnixCCompiler
>     customize UnixCCompiler using build_ext_subclass
>     building 'pmdarima.__check_build._check_build' extension
>     compiling C sources
>     C compiler: gcc -pthread -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC
> 
>     creating build/temp.linux-x86_64-3.6/pmdarima
>     creating build/temp.linux-x86_64-3.6/pmdarima/__check_build
>     compile options: '-I/usr/local/lib64/python3.6/site-packages/numpy/core/include -I/usr/local/lib64/python3.6/site-packages/numpy/core/include -I/usr/include/python3.6m -c'
>     gcc: pmdarima/__check_build/_check_build.c
>     gcc -pthread -shared -g build/temp.linux-x86_64-3.6/pmdarima/__check_build/_check_build.o -L/usr/lib64 -lpython3.6m -o build/lib.linux-x86_64-3.6/pmdarima/__check_build/_check_build.cpython-36m-x86_64-linux-gnu.so
>     building 'pmdarima.arima._arima' extension
>     compiling C sources
>     C compiler: gcc -pthread -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC
> 
>     creating build/temp.linux-x86_64-3.6/pmdarima/arima
>     compile options: '-Ipmdarima/arima -I/usr/local/lib64/python3.6/site-packages/numpy/core/include -Ipmdarima/arima/_arima_fast_helpers.h -I/usr/local/lib64/python3.6/site-packages/numpy/core/include -I/usr/include/python3.6m -c'
>     gcc: pmdarima/arima/_arima.c
>     cc1: error: pmdarima/arima/_arima_fast_helpers.h: not a directory
>     error: Command "gcc -pthread -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -Ipmdarima/arima -I/usr/local/lib64/python3.6/site-packages/numpy/core/include -Ipmdarima/arima/_arima_fast_helpers.h -I/usr/local/lib64/python3.6/site-packages/numpy/core/include -I/usr/include/python3.6m -c pmdarima/arima/_arima.c -o build/temp.linux-x86_64-3.6/pmdarima/arima/_arima.o -MMD -MF build/temp.linux-x86_64-3.6/pmdarima/arima/_arima.o.d" failed with exit status 1
>     ----------------------------------------
> ERROR: Command errored out with exit status 1: /usr/bin/python3.6 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-huof5vb0/pmdarima/setup.py'"'"'; __file__='"'"'/tmp/pip-install-huof5vb0/pmdarima/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-51fufzm6/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.6m/pmdarima Check the logs for full command output.
> 

### To Reproduce

# pip3 install pmdarima

### Versions

```shell
# uname -a
Linux iZbp171hbwz9f2nl9bl97aZ 2.6.32-754.28.1.el6.x86_64 #1 SMP Wed Mar 11 18:38:45 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
# pip3 --version
pip 20.0.2 from /usr/local/lib/python3.6/site-packages/pip (python 3.6)
```

### Expected Behavior

Install successfully

### Actual Behavior

Install failed

**Comment by aaronreidsmith** [comment]
Is there a reason to use such an old version of Linux? I believe the 2.6.32 kernel was end-of-lifed in 2016 ([source](https://en.wikipedia.org/wiki/Linux_kernel_version_history)). Additionally, Python 3.6 was [end-of-lifed in December 2021](https://endoflife.date/python) (and we have removed support for it in #472).

We pre-build binaries for Linux using [manylinux](https://github.com/pypa/manylinux). Is your OS listed in their supported versions? If so, then this is something we should dig into. Otherwise I think this is just a lack of support due to deprecated technologies.

**Comment by tgsmith61591** [comment]
Any update on this @sinall ? Is this still an issue?

**Comment by sinall** [comment]
I works on upgraded CentOS.
