### ISSUE TITLE
Where is it possible to set parameter 'max_lag' when using pmd.arima.autoarima ?

### ISSUE THREAD

**Issue by mhaslehner** [alkaline-ml/pmdarima#487]
### Describe the question you have

Hello,
I am new to the subject. 

Question 1:
When I run my code for some time_series
model = auto_arima(time_series, d = ndiffs_needed, start_p=1, m=12), I get an error of the type 
'**All lag values up to 'maxlag' produced singular matrices. Consider using a longer series, a different lag term or a different test**.'  I am trying to analyse the error.

Where is it possible to change the parameter  _max_lag_ , as this parameter does not appear among the parameters of the autoarima function. Is it max_p? 

Question 2: 
Where can we find documentation or any explanation of the meaning of the parameter out_of_sample_size ?

Thanks

**Comment by tgsmith61591** [comment]
Hello, this error is produced [in the OCSB test](https://github.com/alkaline-ml/pmdarima/blob/master/pmdarima/arima/seasonality.py#L540) when the test statistic fails to produce a non-singular matrix.

Note that [`max_lag`](https://github.com/alkaline-ml/pmdarima/blob/master/pmdarima/arima/seasonality.py#L421) can be passed to the seasonality test in the `auto_arima` function via the [`seasonal_test_args`](https://github.com/alkaline-ml/pmdarima/blob/master/pmdarima/arima/auto.py#L360) argument:

```python
pm.auto_arima(y, X, m=m, seasonal_test_args={"max_lag": 5})
```

As for documentation on `out_of_sample_size` please see the [API Reference](https://alkaline-ml.com/pmdarima/modules/generated/pmdarima.arima.ARIMA.html#pmdarima.arima.ARIMA)
