### ISSUE TITLE
Will support for exogenous variables be removed?

### ISSUE THREAD

**Issue by paulsbrookes** [alkaline-ml/pmdarima#488]
### Describe the question you have

I have noticed comments in the code which suggest there is a plan to remove support for exogenous variables. For example in line 779 of pmdarima.arima.arima.ARIMA.predict_in_sample I see the following:

        check_is_fitted(self, 'arima_res_')

        # Temporary shim until we remove `exogenous` support completely
        X, kwargs = pm_compat.get_X(X, **kwargs)

When is this change planned?

**Comment by aaronreidsmith** [comment]
Support for exogenous variables will not be removed, the argument is just being renamed to `X`. See [the RFC](https://alkaline-ml.com/pmdarima/rfc/372-exog-to-x.html) for more details around _why_ it was changed.

As far as _when_ it will be changed, we plan to make the cutover in version 2 (which we don't have a release date for yet). Right now you will [get a warning](https://github.com/alkaline-ml/pmdarima/blob/accd2e66409b583a30580bd8f2588fe412d9b7f5/pmdarima/compat/pmdarima.py#L17-L23) if you pass in the `exogenous` kwarg. If you are doing so in your code, simply change it to `X` and the warning will disappear and you will be compatible with future versions.

**Comment by paulsbrookes** [comment]
Thank you.
