### ISSUE TITLE
Unable to cross-compile due to pre-build check

### ISSUE THREAD

**Issue by jonashaag** [alkaline-ml/pmdarima#503]
When cross-compiling for OSX ARM64, this line fails because `test_program` can not be run on the machine: https://github.com/alkaline-ml/pmdarima/blob/48790650f3b81401c6953f32dfb612f9ff25af98/pmdarima/_build_utils/pre_build_helpers.py#L55

I worked around this problem in https://github.com/conda-forge/pmdarima-feedstock/pull/29 by removing the pre-build check.

Maybe we can skip the pre-build check when cross-compiling.

**Comment by aaronreidsmith** [comment]
Thanks for bringing this up! I've got a [branch](https://github.com/alkaline-ml/pmdarima/tree/osx-cross-compile) started for this. That file is mostly adapted from Scikit-learn and they seem to skip it on cross-compiles too. We'll try to get it in the next release!

**Comment by aaronreidsmith** [comment]
With #513 you should be able to build using `PYTHON_CROSSENV=true` and it will skip that check and you should be good. Also, as of 2.0.1 (released today) we deploy a wheel for M1 macOS so you may not need to cross compile!

**Comment by tomasvanpottelbergh** [comment]
Great, thanks a lot for that! Confirmed working in the latest conda-forge build: https://github.com/conda-forge/pmdarima-feedstock/pull/33
