### ISSUE TITLE
Adding bounds for numpy in the build requirements and Adding version for build from source

### ISSUE THREAD

**Issue by fnhirwa** [alkaline-ml/pmdarima#579]
### Is your feature request related to a problem? Please describe.

Currently when I install the library from pypi, with the current version of numpy greater than 2, `pmdarima` raises error of binaries incompatibility, this requires users to freeze the numpy to the version greater than `1.21.2` yet less than `2.0`.

Should you add bounds to the requirements inplace during the implementation of `numpy 2` support https://github.com/alkaline-ml/pmdarima/pull/578 this will prevent users from usually handling the version errors manually.

Another issue I noticed when  I built the library from source is that the version is fixed to `0.0.0`
![image](https://github.com/user-attachments/assets/0a2565b8-553a-4df5-8247-a88d2e47aa05)

I understand that you decided to make it default to `0.0.0` for local development and non-tagged commits bumping the version in the `__init__` file at every release would be very easy for bug reporting and no confusion for those installing the library from the source. 

### Describe the solution you'd like

Changing the `requirements.txt` file with version bounds https://github.com/alkaline-ml/pmdarima/blob/c33a01768dfaf65cadfa666420e75548b8587011/requirements.txt#L3 to `numpy>=1.21.2, <2.0`

Tried this locally and when I added bounds using `make develop && make install` gave me version less than `numpy 2` and when the bound was removed I was getting the latest numpy version.

### Describe alternatives you've considered

If this PR https://github.com/alkaline-ml/pmdarima/pull/578 could be quickly merged we should not need these requirements modifications.

**Comment by facundoq** [comment]
Hey! Since this #578 is almost a year old, would you consider merging this into the current version of `pmdarima`?
