### ISSUE TITLE
pdarima with missing values

### ISSUE THREAD

**Issue by pilipentseva** [alkaline-ml/pmdarima#584]
### Describe the bug

I am using pdarima to check replication of R auto.arima results for our ARIMA model and noticed that if auto.arima in R handles missing values itself and does not need pre processing, pdarima raises an issue and refuses to run through unless I do smth with missing values: does it mean that pdarima won't run with missing values? (that is a pity for the case when resuls should be reproduced as I explained :( )

### To Reproduce

works only if NAs are not present:

    # Do ARMA model
    data_vector = data[data['Date'] <= first_jan5][rate_column]
    
    # Fit the model with proper stationarity handling
    best_fit = auto_arima(data_vector, stationary=is_stationary, information_criterion='bic', stepwise=False, 
                          start_p=0, start_q=0, max_p=5, max_q=5, seasonal=False, suppress_warnings=True)
    

### Versions

```shell
# Do ARMA model
    data_vector = data[data['Date'] <= first_jan5][rate_column]
    
    # Fit the model with proper stationarity handling
    best_fit = auto_arima(data_vector, stationary=is_stationary, information_criterion='bic', stepwise=False, 
                          start_p=0, start_q=0, max_p=5, max_q=5, seasonal=False, suppress_warnings=True)
```

### Expected Behavior

expect to treat missing values

### Actual Behavior

stops running and does not run through

**Comment by tgsmith61591** [comment]
It's not a bug. How would you expect missing values to be handled? Should they be ignored? Interpolated? Filled by some other value?

We leave this to the programmer, since there are many ways to solve this problem and we don't presume to know your use case.

**Comment by pilipentseva** [comment]
> It's not a bug. How would you expect missing values to be handled? Should they be ignored? Interpolated? Filled by some other value?
> 
> We leave this to the programmer, since there are many ways to solve this problem and we don't presume to know your use case.

Thanks a lot! But how would I mimique then auto.arima automatic logic for dealing with missing values as in R auto.arima automatically done with Kalman Filter? I would set method = "mle"?
